import * as T from 'three';
import {WORLD_LIMIT,district} from './hood-layout';
import {buildRoadNetwork} from './hood-roads';
import {BUILDINGS,buildNeighborhood} from './hood-buildings';
import {shoulderFrame} from './hood-camera';
import {addResidents} from './hood-npcs';
import {dressNeighborhood} from './hood-dressing';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GUNS,CARS,restoreSave,purchase,intersects,type Save} from './hood-state';
export type Shop='corner'|'weapons'|'dealer'|'repair'|'police';
export type HUD={ready:boolean;error:string;cash:number;ammo:number;reserve:number;gun:string;health:number;stamina:number;heat:number;speed:number;driving:boolean;prompt:string;message:string;shop:Shop|null;mission:string;avatar:number;ownedGuns:string[];ownedCars:string[];car:string;mapX:number;mapZ:number;active:boolean;location:string};
export const PLACES:[Shop,string,number,number,number][]=BUILDINGS.filter(b=>b.kind!=='home').map(b=>[b.kind as Shop,b.name,b.x,b.z,b.color]);
export function createHood(host:HTMLElement,publish:(h:HUD)=>void){
 let save:Save;try{save=restoreSave(localStorage.getItem('cryptodoodz-hood-v1'))}catch{save=restoreSave(null)}
 const scene=new T.Scene();scene.background=new T.Color(0xbacbd0);scene.fog=new T.Fog(0xbacbd0,130,300);
 const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);
 const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','CryptoDoodz neighborhood. WASD move, Shift sprint, mouse aim, click shoot, E interact, F drive.');
 const camera=new T.PerspectiveCamera(57,1,.1,360);scene.add(new T.HemisphereLight(0xcde7ff,0x8c765c,1.7));
 const sun=new T.DirectionalLight(0xffd5a1,2.5);sun.position.set(-35,40,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=70;sun.shadow.camera.bottom=-70;sun.shadow.camera.far=150;sun.shadow.bias=-.001;scene.add(sun);
 const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();const unit=new T.BoxGeometry(1,1,1);geometries.add(unit);const mats=new Map<number,T.MeshStandardMaterial>();
 function mat(c:number){if(!mats.has(c)){const m=new T.MeshStandardMaterial({color:c,roughness:.85});mats.set(c,m);materials.add(m)}return mats.get(c)!}
 function box(w:number,h:number,d:number,x:number,y:number,z:number,c:number,parent:T.Object3D=scene){const m=new T.Mesh(unit,mat(c));m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function sign(text:string,x:number,y:number,z:number,w:number,parent:T.Object3D=scene){const c=document.createElement('canvas');c.width=1024;c.height=160;const ctx=c.getContext('2d')!;ctx.fillStyle='#15272b';ctx.fillRect(0,0,1024,160);ctx.fillStyle='#fff2cc';ctx.font='bold 72px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,82,980);const tex=new T.CanvasTexture(c);textures.add(tex);tex.colorSpace=T.SRGBColorSpace;const m=new T.MeshBasicMaterial({map:tex,side:T.DoubleSide});materials.add(m);const g=new T.PlaneGeometry(w,w/6.4);geometries.add(g);const p=new T.Mesh(g,m);p.position.set(x,y,z);parent.add(p);return p}
 const roads=buildRoadNetwork(scene,sign);
 const obstacles:{x:number;z:number;w:number;d:number}[]=[],solid:T.Object3D[]=[];
 const buildings=buildNeighborhood(scene,box,sign,obstacles,solid),doors=buildings.services;
 for(let i=0;i<16;i++){const x=i%2?11:-11,z=-58+Math.floor(i/2)*16;box(.16,5,.16,x,2.5,z,0x384b50);box(1.4,.2,.5,x+.5,5,z,0xe4d19c)}
 // Safe arcade range: shooting targets here carries no police heat.
 box(19,.2,13,-46,.1,25,0xbaa88b);const wall=box(20,5,.5,-46,2.5,32,0x59696e);solid.push(wall);obstacles.push({x:-46,z:32,w:20,d:.5});sign('TARGET RANGE  /  +$25',-46,4,31.7,16).rotation.y=Math.PI;
 const targets:{mesh:T.Mesh;hp:number;timer:number}[]=[];
 for(let i=0;i<5;i++){const mesh=box(1.1,1.5,.3,-53+i*3.5,1.8,29,0xdc704e);box(.15,1.1,.15,-53+i*3.5,.55,29,0x414e56);targets.push({mesh,hp:100,timer:0});solid.push(mesh);mesh.userData.target=true}
 const player=new T.Group();scene.add(player);player.position.set(0,.1,11);let avatar:T.Group|undefined,mixer:T.AnimationMixer|undefined,actions=new Map<string,T.AnimationAction>(),anim='',loadTicket=0;
 const weapon=new T.Group();let hand:T.Object3D|undefined;box(.09,.13,.28,0,0,.10,0x26313b,weapon);box(.085,.19,.08,0,-.09,.02,0x364550,weapon);
 function carModel(color:number,police=false){const g=new T.Group();box(1.9,.65,3.8,0,.7,0,color,g);box(1.6,.65,1.8,0,1.32,-.1,0x344d5c,g);box(1.7,.12,1.9,0,1.69,-.1,color,g);for(const x of [-1,1])for(const z of [-1.15,1.15])box(.28,.65,.65,x,.43,z,0x242a30,g);for(const x of [-.65,.65]){box(.35,.18,.07,x,.85,1.92,0xf7e8b0,g);box(.35,.15,.07,x,.85,-1.92,0xba524a,g)}if(police){box(.6,.16,.3,-.3,1.83,0,0x4281d2,g);box(.6,.16,.3,.3,1.83,0,0xdf5257,g)}scene.add(g);return g}
 let car=carModel(CARS.find(c=>c.id===save.car)!.color);car.position.set(5,.08,14);const policeCar=carModel(0xe3e4d9,true);policeCar.position.set(-12,.08,-8);
 const dressing=dressNeighborhood(scene,PLACES);const residents=addResidents(scene);
 let ready=false,error='',active=false,dead=false,shop:Shop|null=null,health=100,stamina=100,heat=0,mag=17,reloading=0,shootTime=0,fireCooldown=0,jumpTime=0,speed=0,driving=false,yaw=Math.PI,pitch=.16,drag=false,held=false,message='Welcome to the block. Your Glock and compact car are ready.',msgUntil=8,time=0,lastEmit=0,saveClock=0,ticketCooldown=0,crashCooldown=0,location='The Block';
 let mission:typeof doors[number]|null=null;const keys=new Set<string>();const ray=new T.Raycaster(),desired=new T.Vector3(),focus=new T.Vector3(),pivot=new T.Vector3();const effects:{mesh:T.Mesh;life:number}[]=[];
 function persist(){try{localStorage.setItem('cryptodoodz-hood-v1',JSON.stringify(save))}catch{/* Private browsing can disable local saves. */}}
 function tell(s:string){message=s;msgUntil=time+5;emit()}
 function gun(){return GUNS.find(g=>g.id===save.gun)!}
 function play(name:string){if(anim===name)return;actions.get(anim)?.fadeOut(.13);const a=actions.get(name);a?.reset().fadeIn(.13).play();anim=name}
 async function loadAvatar(id:number){const ticket=++loadTicket;ready=false;error='';emit();try{const gltf=await new GLTFLoader().loadAsync(`/cryptodoodz/models/${String(id).padStart(4,'0')}.glb`);if(dead||ticket!==loadTicket){freeModel(gltf.scene);return}if(avatar){weapon.removeFromParent();player.remove(avatar);freeModel(avatar)}avatar=gltf.scene;player.add(avatar);avatar.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});hand=avatar.getObjectByName('hand.R')??avatar.getObjectByName('handR');if(hand){hand.add(weapon);weapon.position.set(0,.08,0);weapon.rotation.set(-Math.PI/2,0,0)}mixer=new T.AnimationMixer(avatar);actions=new Map(gltf.animations.map(c=>[c.name,mixer!.clipAction(c)]));for(const [name,a]of actions)if(!['Idle','Walk','Run'].includes(name)){a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true}anim='';play('Idle');save.avatar=id;ready=true;persist();emit()}catch{error='The Dood could not load. Check your connection and retry.';emit()}}
 function freeModel(root:T.Object3D){root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}})}
 function nearest(){return doors.find(d=>Math.abs(player.position.x-d.building.x)<d.building.w/2-.25&&Math.abs(player.position.z-d.building.z)<d.building.d/2-.25&&Math.hypot(player.position.x-d.x,player.position.z-d.z)<2.4)}
 function emit(){if(dead)return;const near=nearest();publish({ready,error,cash:save.cash,ammo:mag,reserve:save.ammo,gun:gun().name,health,stamina,heat,speed:Math.abs(speed)*3.6,driving,prompt:driving?'F · Exit vehicle':Math.hypot(player.position.x-car.position.x,player.position.z-car.position.z)<3.4?'F · Drive car':near?`E · ${near.name}`:'',message:time<msgUntil?message:'',shop,mission:mission?`Deliver to ${mission.name} · $180`:'Walk inside the police station for delivery jobs',avatar:save.avatar,ownedGuns:[...save.guns],ownedCars:[...save.cars],car:save.car,mapX:player.position.x,mapZ:player.position.z,active,location})}
 function clear(){keys.clear();held=false;drag=false}
 function pause(){active=false;clear();if(document.pointerLockElement===canvas)document.exitPointerLock();emit()}
 function resume(){if(!ready)return;shop=null;active=true;canvas.focus();emit()}
 function reload(){if(!reloading&&mag<gun().capacity&&save.ammo>0){reloading=1.2;tell('Reloading…')}}
 function shoot(){if(!active||shop||driving||fireCooldown>0||reloading)return;if(mag<=0){reload();return}mag--;fireCooldown=gun().interval;shootTime=.67;anim='';play('Shoot');
  player.rotation.y=yaw;ray.setFromCamera(new T.Vector2(0,0),camera);ray.far=80;let hit=ray.intersectObjects(solid,false).find(h=>h.object.visible);const end=hit?.point??ray.ray.at(65,new T.Vector3());const start=player.position.clone().add(new T.Vector3(-.3,1.3,0));if(hand)weapon.getWorldPosition(start);ray.set(start,end.clone().sub(start).normalize());ray.far=start.distanceTo(end);const cover=ray.intersectObjects(solid,false).find(h=>h.object.visible);if(cover){hit=cover;end.copy(cover.point)}const delta=end.clone().sub(start);const line=box(.025,.025,delta.length(),0,0,0,0xffe9a0);line.position.copy(start).addScaledVector(delta,.5);line.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),delta.normalize());effects.push({mesh:line,life:.07});
  const target=targets.find(t=>t.mesh===hit?.object);if(target){target.hp-=gun().damage;if(target.hp<=0){target.mesh.visible=false;target.timer=5;save.cash+=25;tell('Target cleared · +$25');persist()}}else if(Math.hypot(player.position.x+46,player.position.z-25)>15){heat=Math.min(3,heat+.3)}emit()
 }
 function move(x:number,z:number,r:number,obj:T.Object3D){let collided=false;for(const [dx,dz]of [[x,0],[0,z]]){const nx=T.MathUtils.clamp(obj.position.x+dx,-WORLD_LIMIT,WORLD_LIMIT),nz=T.MathUtils.clamp(obj.position.z+dz,-WORLD_LIMIT,WORLD_LIMIT);if(!intersects(nx,nz,r,obstacles))obj.position.set(nx,obj.position.y,nz);else collided=true}return collided}
 function toggleCar(){if(driving){const candidates=[new T.Vector3(2,0,0),new T.Vector3(-2,0,0),new T.Vector3(0,0,-3)].map(v=>v.applyAxisAngle(new T.Vector3(0,1,0),car.rotation.y).add(car.position));const p=candidates.find(p=>!intersects(p.x,p.z,.4,obstacles));if(!p){tell('Move the car away from the wall first.');return}player.position.set(p.x,.1,p.z);driving=false;player.visible=true;speed=0}else if(player.position.distanceTo(car.position)<3.5){driving=true;player.visible=false;yaw=car.rotation.y;clear();tell('W/S accelerate & reverse · A/D steer · F exit')}emit()}
 function interact(){if(driving)return;const n=nearest();if(!n)return;if(mission?.kind===n.kind){save.cash+=180;mission=null;persist();tell('Delivery complete · +$180');return}shop=n.kind;clear();if(document.pointerLockElement===canvas)document.exitPointerLock();emit()}
 function keydown(e:KeyboardEvent){if(!active||shop||document.activeElement!==canvas&&document.pointerLockElement!==canvas)return;if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','Space','KeyE','KeyF','KeyR'].includes(e.code))e.preventDefault();if(e.code==='Escape'){pause();return}keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE')interact();if(e.code==='KeyF')toggleCar();if(e.code==='KeyR')reload();if(e.code==='Space'&&!driving&&jumpTime<=0){jumpTime=1.333;anim='';play('Jump')}}
 function pointer(e:PointerEvent){if(!active||shop)return;canvas.focus();if(e.button===2){drag=true;return}if(e.button===0){if(document.pointerLockElement!==canvas){try{canvas.requestPointerLock()?.catch(()=>{})}catch{/* right-drag fallback */}}held=true;shoot()}}
 function mouse(e:MouseEvent){if(!active||shop||document.pointerLockElement!==canvas&&!drag)return;yaw-=e.movementX*.0025;pitch=T.MathUtils.clamp(pitch+e.movementY*.0025,-.1,.85)}
 function keyup(e:KeyboardEvent){keys.delete(e.code)}function pointerup(){held=false;drag=false}function lock(){if(document.pointerLockElement!==canvas){clear();if(!shop)active=false;emit()}}function context(e:Event){e.preventDefault()}
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',pause);window.addEventListener('pointerup',pointerup);document.addEventListener('mousemove',mouse);document.addEventListener('pointerlockchange',lock);canvas.addEventListener('pointerdown',pointer);canvas.addEventListener('contextmenu',context);
 const ro=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});ro.observe(host);
 const clock=new T.Clock();function update(dt:number){time+=dt;if(active&&!shop&&ready){fireCooldown=Math.max(0,fireCooldown-dt);shootTime=Math.max(0,shootTime-dt);jumpTime=Math.max(0,jumpTime-dt);crashCooldown=Math.max(0,crashCooldown-dt);ticketCooldown=Math.max(0,ticketCooldown-dt);if(held&&gun().automatic)shoot();if(reloading){reloading=Math.max(0,reloading-dt);if(!reloading){const n=Math.min(gun().capacity-mag,save.ammo);mag+=n;save.ammo-=n;persist()}}
 const forward=Number(keys.has('KeyW'))-Number(keys.has('KeyS')),side=Number(keys.has('KeyD'))-Number(keys.has('KeyA'));
 if(driving){const max=CARS.find(c=>c.id===save.car)!.speed;speed+=forward*dt*10;speed*=Math.pow(forward?.992:.955,dt*60);speed=T.MathUtils.clamp(speed,-8,max*(health/100*.65+.35));car.rotation.y-=side*dt*1.45*T.MathUtils.clamp(speed/7,-1,1);if(move(Math.sin(car.rotation.y)*speed*dt,Math.cos(car.rotation.y)*speed*dt,1.25,car)&&!crashCooldown){health=Math.max(10,health-Math.abs(speed)*2);speed*= -.2;crashCooldown=.6;tell('Vehicle damaged. Visit Repair & Tune.')}player.position.copy(car.position);yaw=T.MathUtils.lerp(yaw,car.rotation.y,.045)}else{const length=Math.hypot(forward,side);const sprint=length>0&&(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&stamina>0;stamina=T.MathUtils.clamp(stamina+(sprint?-23:15)*dt,0,100);if(length){const pace=sprint?7:3.6;const dx=(Math.sin(yaw)*forward-Math.cos(yaw)*side)/length,dz=(Math.cos(yaw)*forward+Math.sin(yaw)*side)/length;move(dx*pace*dt,dz*pace*dt,.37,player);if(!shootTime)player.rotation.y=Math.atan2(dx,dz)}if(!shootTime&&!jumpTime)play(length?(sprint?'Run':'Walk'):'Idle')}
 heat=Math.max(0,heat-dt*.018);if(heat>.4){const direction=player.position.clone().sub(policeCar.position);const distance=direction.length();if(distance>4){direction.normalize();move(direction.x*dt*6,direction.z*dt*6,1.2,policeCar);policeCar.rotation.y=Math.atan2(direction.x,direction.z)}if(distance<5&&!ticketCooldown){save.cash=Math.max(0,save.cash-75);heat=0;ticketCooldown=15;persist();tell('Police citation · $75. Use the target range.')}}
 for(const t of targets)if(t.timer>0){t.timer-=dt;if(t.timer<=0){t.hp=100;t.mesh.visible=true}}
 residents.update(dt,player.position);mixer?.update(dt);
 saveClock+=dt;if(saveClock>10){saveClock=0;persist()}
 }
 for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0){scene.remove(effects[i].mesh);effects.splice(i,1)}}
 sun.position.set(player.position.x-35,40,player.position.z+25);sun.target.position.set(player.position.x,0,player.position.z);sun.target.updateMatrixWorld();
 const room=buildings.update(player.position);location=room?.name??district(player.position.x,player.position.z);
 shoulderFrame(player.position,yaw,pitch,driving,pivot,focus,desired,!!room);
 // Sweep from the player to the shoulder camera, including the lateral offset.
 const distance=desired.distanceTo(pivot);ray.set(pivot,desired.clone().sub(pivot).normalize());ray.far=distance;
 const obstruction=ray.intersectObjects(solid,false).find(h=>h.object.visible);
 if(obstruction)desired.copy(ray.ray.at(Math.max(.15,obstruction.distance-.25),new T.Vector3()));
 desired.y=Math.max(.45,desired.y);camera.position.copy(desired);
 // Preserve the aim direction when a wall pushes the camera inward.
 camera.lookAt(camera.position.clone().add(new T.Vector3(Math.sin(yaw)*Math.cos(pitch),-Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch))));camera.updateMatrixWorld();
 if(time-lastEmit>.12){lastEmit=time;emit()}renderer.render(scene,camera)
 }
 camera.position.set(0,4,4);renderer.setAnimationLoop(()=>update(Math.min(clock.getDelta(),.05)));loadAvatar(save.avatar);
 function buy(kind:'gun'|'car',id:string){const result=purchase(save,kind,id);if(result.ok){if(kind==='gun'){save.ammo=Math.min(999,save.ammo+mag);mag=Math.min(gun().capacity,save.ammo);save.ammo-=mag;weapon.scale.setScalar(id==='glock'?1:1.35)}else{scene.remove(car);freeModelUniqueCar(car);car=carModel(CARS.find(c=>c.id===save.car)!.color);car.position.set(5,.08,14);health=100}persist()}tell(result.message)}
 function freeModelUniqueCar(_car:T.Object3D){/* Car meshes use shared world geometry/materials. */}
 return{resume,pause,buy,closeShop:()=>{shop=null;resume()},setAvatar:(id:number)=>{pause();loadAvatar(Math.max(1,Math.min(1000,Math.trunc(Number(id)||1))))},service:(type:string)=>{if(type==='job'){mission=doors.filter(d=>d.kind!=='police')[Math.floor(Math.random()*4)];tell(`Delivery accepted: ${mission.name}`)}else if(type==='ammo'){if(save.cash<40){tell('Ammo costs $40');return}save.cash-=40;save.ammo=Math.min(999,save.ammo+85);tell('85 rounds added')}else if(type==='repair'){if(save.cash<90){tell('Repairs cost $90');return}save.cash-=90;health=100;tell('Vehicle repaired')}else if(type==='snack'){if(save.cash<15){tell('Snacks cost $15');return}save.cash-=15;stamina=100;tell('Stamina restored')}persist();emit()},dispose:()=>{dead=true;persist();clear();if(document.pointerLockElement===canvas)document.exitPointerLock();ro.disconnect();renderer.setAnimationLoop(null);residents.dispose();dressing.dispose();buildings.dispose();roads.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',pause);window.removeEventListener('pointerup',pointerup);document.removeEventListener('mousemove',mouse);document.removeEventListener('pointerlockchange',lock);canvas.removeEventListener('pointerdown',pointer);canvas.removeEventListener('contextmenu',context);if(avatar){weapon.removeFromParent();freeModel(avatar)}geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();canvas.remove()}};
}



