<script lang="ts">
 import {onMount} from 'svelte';import {BrowserProvider,Contract,JsonRpcProvider} from 'ethers';import DoodViewer from '$lib/components/DoodViewer.svelte';import {wallet,connect,walletProvider,switchToBase} from '$lib/web3/wallet';
 const abi=['function totalSupply() view returns(uint256)','function mintedBy(address) view returns(uint256)','function mintOpen() view returns(bool)','function mint(uint256 quantity)'];
 const clips=['Idle','Walk','Run','Jump','Shoot','Wave'] as const;
 let address=$state(''),supply=$state(0),used=$state(0),open=$state(false),ready=$state(false),busy=$state(false),message=$state(''),tx=$state(''),qty=$state(1),id=$state(1),clip=$state<(typeof clips)[number]>('Idle');let provider:JsonRpcProvider|undefined;
 const remaining=$derived(Math.max(0,Math.min(5-used,1000-supply)));
 function show(n:number){id=Math.max(1,Math.min(1000,Math.trunc(Number(n)||1)));if(typeof history!=='undefined')history.replaceState(null,'',`?id=${id}`);}
 function step(delta:number){show(((id-1+delta+1000)%1000)+1);}
 function typeId(e:Event){const raw=(e.currentTarget as HTMLInputElement).value;if(raw==='')return;const n=Number(raw);if(Number.isInteger(n))show(n);}
 async function refresh(){if(!address||!provider)return;try{const c=new Contract(address,abi,provider);const [s,o,u]=await Promise.all([c.totalSupply(),c.mintOpen(),$wallet.address?c.mintedBy($wallet.address):0]);supply=Number(s);open=o;used=Number(u);ready=true;qty=Math.max(1,Math.min(qty,remaining))}catch{message='Unable to read Base right now. Please retry.'}}
 $effect(()=>{const a=$wallet.address;if(a&&address)void refresh()});
 onMount(()=>{provider=new JsonRpcProvider('https://mainnet.base.org');const n=Number(new URL(location.href).searchParams.get('id'));if(Number.isInteger(n)&&n>=1&&n<=1000)id=n;fetch('/cryptodoodz/contract.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(c=>{address=c.address;return refresh()}).catch(()=>message='Collection setup is in progress.');const timer=setInterval(refresh,15000);return()=>{clearInterval(timer);provider?.destroy()}});
 async function mint(){busy=true;message='';try{if(!$wallet.connected){await connect();return}if($wallet.chainId!==8453){await switchToBase();return}await refresh();if(!ready||!open||qty>remaining)throw Error('Minting is unavailable for this quantity.');const p=new BrowserProvider(await walletProvider());if((await p.getNetwork()).chainId!==8453n)throw Error('Switch to Base mainnet.');const c=new Contract(address,abi,await p.getSigner());const t=await c.mint(qty);tx=t.hash;message='Transaction submitted. Waiting for confirmation…';await t.wait();message='Your CryptoDoodz are minted!';await refresh()}catch(e){message=e instanceof Error?(('shortMessage' in e?String(e.shortMessage):e.message)):'Mint was not completed.'}finally{busy=false}}
</script>
<svelte:head><title>CryptoDoodz — Free mint on Base</title><meta name="description" content="1,000 animated CryptoDoodz. Free mint on Base, maximum five mints per wallet."/></svelte:head>
<main class="doodz"><nav><a href="/">← Cloudacre Oil</a><span>BASE MAINNET</span></nav><div class="layout"><section><DoodViewer {id} {clip}/><div class="preview"><button type="button" onclick={()=>step(-1)} aria-label="Previous Dood">←</button><label>Preview #<input type="number" min="1" max="1000" value={id} oninput={typeId}/></label><button type="button" onclick={()=>step(1)} aria-label="Next Dood">→</button><select aria-label="Animation" bind:value={clip}>{#each clips as c}<option value={c}>{c}</option>{/each}</select></div><p class="muted">Drag to rotate. Preview choice does not select the NFT you mint.</p></section><section class="mint"><p class="eyebrow">1,000 ORIGINAL 3D CHARACTERS</p><h1>CryptoDoodz</h1><p class="intro">Pick up a Dood.<br/>Bring him to life.</p><div class="stats"><div><strong>FREE</strong><span>Network gas applies</span></div><div><strong>{ready?supply:'—'} / 1,000</strong><span>Minted</span></div></div><p>Up to 5 mints per wallet, for the life of the collection. Every Dood includes six animations.</p><label class="quantity">Quantity <select bind:value={qty}>{#each [1,2,3,4,5] as n}<option value={n} disabled={n>remaining}>{n}</option>{/each}</select></label><button class="primary" onclick={mint} disabled={busy||($wallet.connected&&$wallet.chainId===8453&&(!ready||!open||remaining===0))}>{busy?'Working…':!$wallet.connected?'Connect wallet':$wallet.chainId!==8453?'Switch to Base':!ready?'Loading…':supply>=1000?'Sold out':!open?'Mint opens soon':remaining===0?'Wallet limit reached':`Mint ${qty} for free`}</button>{#if $wallet.address}<p class="muted">{$wallet.address.slice(0,6)}…{$wallet.address.slice(-4)} · {used} / 5 minted</p>{/if}<p role="status">{message}</p>{#if tx}<a href={`https://basescan.org/tx/${tx}`} target="_blank" rel="noreferrer">View transaction ↗</a>{/if}{#if address}<a class="contract" href={`https://basescan.org/address/${address}`} target="_blank" rel="noreferrer">View collection contract ↗</a>{/if}</section></div></main>
<style>.doodz{min-height:100vh;background:#f0eee8;color:#18232b;padding:28px clamp(20px,5vw,80px);font-family:Arial,sans-serif}.doodz nav{display:flex;justify-content:space-between;margin-bottom:35px;font-size:14px}.doodz a{color:inherit}.layout{display:grid;grid-template-columns:1.3fr 1fr;gap:54px;max-width:1300px;margin:auto}.mint{padding-top:28px}.eyebrow{letter-spacing:.14em;font-size:13px;font-weight:bold}h1{font-size:clamp(40px,5vw,68px);letter-spacing:-.055em;margin:15px 0}.intro{font-size:30px;line-height:1.25}.stats{display:flex;gap:40px;border-top:1px solid #abb5bb;border-bottom:1px solid #abb5bb;padding:22px 0}.stats strong{font-size:25px;display:block}.stats span,.muted{font-size:14px;color:#56656e}.mint p{line-height:1.6}.preview{display:flex;align-items:center;gap:10px;margin-top:15px}.doodz button,.doodz select,.doodz input{font:inherit;border:1px solid #a3b0b8;border-radius:8px;padding:10px;background:white;color:#18232b}.doodz input{width:90px}.quantity{display:flex;justify-content:space-between;align-items:center;margin:20px 0}.primary{width:100%;background:#233c50!important;color:white!important;font-weight:bold!important;padding:18px!important}.doodz button:disabled{opacity:.55;cursor:not-allowed}.contract{display:block;margin-top:20px;font-size:14px}@media(max-width:850px){.layout{grid-template-columns:1fr;gap:10px}.mint{padding-top:0}.preview{flex-wrap:wrap}}</style>
