import * as THREE from 'three';
const $=id=>document.getElementById(id);
const state={playing:[false,false],volume:[.8,.8],filter:[1,1],tempo:124,cross:.5,master:.65};
let ctx, master, compressor, channels, filters, timer, next=0, step=0, noise, enabled=false;
const flashes=[Array(4).fill(0),Array(4).fill(0)];
function mix(){if(!ctx)return;channels.forEach((g,i)=>g.gain.setTargetAtTime(state.volume[i]*(i?Math.sin(state.cross*Math.PI/2):Math.cos(state.cross*Math.PI/2)),ctx.currentTime,.02));master.gain.setTargetAtTime(state.master*.65,ctx.currentTime,.02);filters.forEach((f,i)=>f.frequency.setTargetAtTime(120*Math.pow(160,state.filter[i]),ctx.currentTime,.03));}
async function audio(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();compressor=ctx.createDynamicsCompressor();master.connect(compressor);compressor.connect(ctx.destination);filters=[0,1].map(()=>{const f=ctx.createBiquadFilter();f.type='lowpass';f.Q.value=.6;f.connect(master);return f});channels=filters.map(f=>{const g=ctx.createGain();g.connect(f);return g});noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;mix();timer=setInterval(schedule,25);next=ctx.currentTime+.05;}await ctx.resume();enabled=true;$('power').textContent='Mute audio';$('power').setAttribute('aria-pressed','true');$('status').textContent='Audio enabled · Start a deck or tap a pad.';}
function tone(d,f,t,len=.2,type='sine',vol=.22,end){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+len);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+len);o.connect(g);g.connect(channels[d]);o.start(t);o.stop(t+len+.01);o.onended=()=>{o.disconnect();g.disconnect()};}
function hiss(d,t,len,cut,vol){const s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=noise;f.type='highpass';f.frequency.value=cut;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+len);s.connect(f);f.connect(g);g.connect(channels[d]);s.start(t);s.stop(t+len);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect()};}
function hit(d,p,t=ctx?.currentTime){if(!ctx||!enabled)return;flashes[d][p]=performance.now()+120;if(d===0){if(p===0)tone(0,155,t,.36,'sine',.7,43);if(p===1){hiss(0,t,.15,1100,.36);tone(0,180,t,.12,'triangle',.17,85)}if(p===2)hiss(0,t,.055,6500,.16);if(p===3)hiss(0,t,.25,4200,.16);}else{const notes=[220,261.63,329.63,440];tone(1,notes[p],t,.4,'triangle',.3);tone(1,notes[p]/2,t,.28,'sine',.25);}}
function schedule(){if(!ctx||ctx.state!=='running')return;if(next<ctx.currentTime)next=ctx.currentTime+.03;while(next<ctx.currentTime+.1){const s=step%16;if(enabled&&state.playing[0]){if(s%4===0)hit(0,0,next);if(s%8===4)hit(0,1,next);if(s%2===0)hit(0,2,next);if(s===14)hit(0,3,next);}if(enabled&&state.playing[1]&&s%2===0){const seq=[0,0,2,1,0,3,2,1];const n=[55,65.406,82.407,110][seq[s/2]];tone(1,n,next,.21,'sawtooth',.17);if(s%4===0)hit(1,seq[s/2],next);}next+=60/state.tempo/4;step++;}}
function reportError(e){$('status').textContent='Audio unavailable: '+e.message;$('status').classList.add('error');}
async function toggle(d){await audio();state.playing[d]=!state.playing[d];update();}
function update(){state.playing.forEach((v,i)=>{$('play'+i).textContent=(v?'Ⅱ Pause ':'▶ Play ')+(i?'B':'A');$('play'+i).setAttribute('aria-pressed',String(v));const stageButton=$('stage-play'+i);stageButton.textContent=(v?'Ⅱ Pause ':'▶ Play ')+(i?'B':'A');stageButton.setAttribute('aria-pressed',String(v));stageButton.setAttribute('aria-label',(v?'Pause track ':'Play track ')+(i?'B':'A'));});$('status').textContent=state.playing.some(Boolean)?'Live · '+state.tempo+' BPM · Drag a platter to scratch.':'Ready · Tap a pad or start a deck.';}
$('power').onclick=async()=>{try{if(enabled){await ctx.suspend();enabled=false;$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false');$('status').textContent='Audio muted';}else await audio();}catch(e){reportError(e)}};
[0,1].forEach(d=>{$('play'+d).onclick=()=>toggle(d).catch(reportError);$('stage-play'+d).onclick=()=>toggle(d).catch(reportError);['Kick','Snare','Hat','Open hat'].forEach((label,p)=>{const b=document.createElement('button');b.textContent=d?['A','C','E','A ↑'][p]:label;b.setAttribute('aria-label',`Deck ${d?'B':'A'} ${b.textContent} pad`);b.onclick=()=>audio().then(()=>hit(d,p)).catch(reportError);$('pads'+d).append(b);});for(let j=0;j<16;j++)$('beats'+d).append(document.createElement('i'));$('vol'+d).oninput=e=>{state.volume[d]=Number(e.target.value)/100;$('v'+d).textContent=e.target.value+'%';mix()};$('filter'+d).oninput=e=>{state.filter[d]=Number(e.target.value)/100;$('f'+d).textContent=e.target.value==='100'?'Open':e.target.value+'%';mix()};});
$('tempo').oninput=e=>{state.tempo=Number(e.target.value);$('bpm').textContent=e.target.value;update()};$('master').oninput=e=>{state.master=Number(e.target.value)/100;$('mastervalue').textContent=e.target.value+'%';mix()};$('cross').oninput=e=>{state.cross=Number(e.target.value)/100;$('blend').textContent=(100-Number(e.target.value))+' / '+e.target.value;mix()};$('help').onclick=()=>{const expanded=$('help').getAttribute('aria-expanded')!=='true';$('help').setAttribute('aria-expanded',String(expanded));$('instructions').classList.toggle('hidden',!expanded)};
document.addEventListener('keydown',e=>{if(e.repeat||['INPUT','BUTTON','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();audio().then(()=>{const on=!state.playing.some(Boolean);state.playing=[on,on];update()}).catch(reportError);}const n=Number(e.key)-1;if(n>=0&&n<8)audio().then(()=>hit(Math.floor(n/4),n%4)).catch(reportError)});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&ctx){ctx.suspend();enabled=false;$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false');$('status').textContent='Audio paused · Tap Enable audio to resume.';}});
// Real, raycastable geometry; no model or network dependencies.
const canvas=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true,alpha:true});}catch(e){$('status').textContent='3D is unavailable on this device. The audio controls below still work.';}
if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
scene.add(new THREE.HemisphereLight(0xabbfff,0x12131d,3));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(0,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-8;key.shadow.camera.right=8;key.shadow.camera.top=8;key.shadow.camera.bottom=-8;scene.add(key);const rim=new THREE.PointLight(0x9e79ff,45);rim.position.set(4,2,-3);scene.add(rim);const green=new THREE.PointLight(0xa8ff67,25);green.position.set(-4,2,0);scene.add(green);
const board=new THREE.Group();scene.add(board);const targets=[],platters=[],pads=[[],[]],knobs=[[],[]];
const mat=(c,m=.4,r=.4)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});const black=mat(0x141820,.65,.3),silver=mat(0x67717f,.85,.24),rubber=mat(0x050609,.1,.8);const colors=[0xafff70,0xb49aff];
function box(w,h,d,x,y,z,material,parent=board){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function cyl(r,h,x,y,z,material,parent=board){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,80),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function label(text,x,y,z,color='#dce3f2',size=.22){const c=document.createElement('canvas');c.width=1024;c.height=128;const g=c.getContext('2d');g.fillStyle=color;g.font='600 54px Arial';g.textAlign='center';g.fillText(text,512,83);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const o=new THREE.Mesh(new THREE.PlaneGeometry(size*8,size),new THREE.MeshBasicMaterial({map:t,transparent:true,depthWrite:false}));o.rotation.x=-Math.PI/2;o.position.set(x,y,z);board.add(o);}
box(10.6,.44,4.9,0,0,0,black);box(10.7,.09,4.96,0,-.16,0,silver);box(10.5,.05,4.8,0,.245,0,mat(0x252b35,.6,.4));for(const x of [-4.7,4.7])for(const z of [-2,2])cyl(.1,.025,x,.287,z,silver);
for(let d=0;d<2;d++){const x=d?3.2:-3.2;const accent=mat(colors[d],.4,.3);accent.emissive=new THREE.Color(colors[d]);accent.emissiveIntensity=.2;cyl(1.56,.08,x,.3,-.12,rubber);cyl(1.48,.1,x,.38,-.12,silver);cyl(1.4,.12,x,.46,-.12,accent);const p=new THREE.Group();p.position.set(x,.54,-.12);board.add(p);const disc=cyl(1.34,.06,0,0,0,rubber,p);disc.userData={kind:'platter',deck:d};targets.push(disc);for(let r=.5;r<1.3;r+=.065){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.006,5,100),silver);ring.rotation.x=Math.PI/2;ring.position.y=.04;p.add(ring)}cyl(.44,.025,0,.045,0,black,p);cyl(.08,.03,0,.07,0,silver,p);box(.055,.015,.3,0,.05,-1.12,accent,p);platters.push(p);label(d?'B  /  ULTRAVIOLET':'A  /  MIDNIGHT',x,.3,-1.99,d?'#c0aaff':'#bdff96',.19);
for(let j=0;j<4;j++){const pad=box(.56,.11,.47,x-1.02+j*.68,.33,1.83,accent.clone());pad.userData={kind:'pad',deck:d,pad:j};targets.push(pad);pads[d].push(pad);}for(let j=0;j<2;j++){const k=cyl(.15,.18,x+(d?-1.8:1.8),.38,-.65+j*.95,silver);knobs[d].push(k);box(.025,.015,.11,k.position.x,.48,k.position.z-.05,accent)} }
label('CRYPTO DOODZ',0,.29,-2.06,'#e3e9f2',.16);label('AFTERHOURS',0,.29,-1.7,'#a9b5c6',.15);
const display=mat(0x9ff779,.1,.5);display.emissive=new THREE.Color(0x7cd55e);display.emissiveIntensity=.3;box(1.35,.04,.49,0,.29,-1.13,rubber);label('SYNC / 4:4',0,.325,-1.12,'#afff70',.14);
for(let i=0;i<2;i++){const x=i?.47:-.47;box(.065,.03,1.32,x,.29,.05,rubber);box(.37,.15,.18,x,.39,-.15,silver);for(let j=0;j<8;j++)box(.085,.02,.1,x+(i?-.19:.19),.29,.65-j*.16,display);}
box(1.45,.04,.09,0,.29,1.38,rubber);const crossKnob=box(.22,.15,.35,0,.38,1.38,silver);label('A     CROSSFADE     B',0,.29,1.96,'#a9b5c6',.13);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.3}));floor.rotation.x=-Math.PI/2;floor.position.y=-.42;floor.receiveShadow=true;scene.add(floor);
let yaw=0,pitch=.83,distance=12.6;function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();distance=camera.aspect<1.4?18:13;}const ro=new ResizeObserver(resize);ro.observe(canvas);
$('reset').onclick=()=>{yaw=0;pitch=.83};const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),touches=new Map();
function pick(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(targets)[0]?.object.userData;}
canvas.addEventListener('pointerdown',e=>{const target=pick(e);canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY,target,last:0});if(target)audio().then(()=>{if(target.kind==='pad')hit(target.deck,target.pad)}).catch(reportError)});
canvas.addEventListener('pointermove',e=>{const t=touches.get(e.pointerId);if(!t)return;const dx=e.clientX-t.x,dy=e.clientY-t.y;if(t.target?.kind==='platter'){platters[t.target.deck].rotation.y+=dx*.035;if(enabled&&performance.now()-t.last>35&&Math.abs(dx)+Math.abs(dy)>1){tone(t.target.deck,100+Math.min(1800,Math.abs(dx)*70),ctx.currentTime,.06,'sawtooth',.1,60);t.last=performance.now();}}else if(!t.target){yaw=Math.max(-.8,Math.min(.8,yaw-dx*.006));pitch=Math.max(.4,Math.min(1.35,pitch+dy*.006));}t.x=e.clientX;t.y=e.clientY;});for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,e=>touches.delete(e.pointerId));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let previous=performance.now();function draw(now){const dt=Math.min((now-previous)/1000,.05);previous=now;camera.position.set(Math.sin(yaw)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,0,0);for(let d=0;d<2;d++){if(enabled&&state.playing[d]&&!reduced&&![...touches.values()].some(t=>t.target?.kind==='platter'&&t.target.deck===d))platters[d].rotation.y-=dt*state.tempo/35;pads[d].forEach((p,j)=>{const lit=flashes[d][j]>now;p.material.emissiveIntensity=lit?2:.18;$('pads'+d).children[j].classList.toggle('hit',lit)});[...$('beats'+d).children].forEach((b,j)=>b.classList.toggle('on',enabled&&state.playing[d]&&j===(step-1)%16));}crossKnob.position.x=(state.cross-.5)*1.25;renderer.render(scene,camera);requestAnimationFrame(draw)}requestAnimationFrame(draw);
// Export the actual sculpture render as the NFT cover, without UI or remote assets.
const exportButton=document.createElement('button');exportButton.className='small';exportButton.textContent='Save cover';exportButton.onclick=()=>{const w=canvas.clientWidth,h=canvas.clientHeight,ratio=renderer.getPixelRatio(),oldAspect=camera.aspect;renderer.setPixelRatio(1);renderer.setSize(3000,3000,false);camera.aspect=1;camera.updateProjectionMatrix();const pos=camera.position.clone();camera.position.set(0,13,13);camera.lookAt(0,0,0);scene.background=new THREE.Color(0x0b0d12);renderer.render(scene,camera);const a=document.createElement('a');a.download='cryptodoodz-afterhours.png';a.href=canvas.toDataURL('image/png');a.click();scene.background=null;camera.position.copy(pos);camera.aspect=oldAspect;camera.updateProjectionMatrix();renderer.setPixelRatio(ratio);renderer.setSize(w,h,false);};document.querySelector('.toolbar').insertBefore(exportButton,$('status'));
}

