import {GUEST_DOOD_ID} from '../player/identity.ts';
import {PerspectiveCamera,Scene,Vector3} from 'three';
import {PlayerAvatar} from '../player/avatar.ts';
type Pose={id:string;character:number;x:number;y:number;z:number;yaw:number;animation:'Idle'|'Walk'|'Run'|'Jump'};
export class Multiplayer {
 private socket?:WebSocket;private disposed=false;private retry?:ReturnType<typeof setTimeout>;private elapsed=0;
 private remotes=new Map<string,{avatar:PlayerAvatar;camera:PerspectiveCamera;pose:Pose}>();
 private authenticate?: (message:string)=>Promise<{address:string;character:number;signature:string}>;
 private mockCharacter=Number(GUEST_DOOD_ID);
 private scene:Scene;private url:string;private room:string;private status:HTMLElement;
 constructor(scene:Scene,url:string,room:string,authenticate?:Multiplayer['authenticate'],mockCharacter=Number(GUEST_DOOD_ID)){this.mockCharacter=mockCharacter;this.authenticate=authenticate;this.scene=scene;this.url=url;this.room=room;this.status=document.createElement('div');this.status.style.cssText='position:fixed;left:20px;bottom:55px;padding:8px 12px;background:#142e25cc;color:#dbe8d2;font:12px Arial;pointer-events:none';document.body.append(this.status);this.connect();}
 private connect(){if(this.disposed)return;this.status.textContent='Connecting to nearby players…';try{const u=new URL(this.url);if(u.protocol!=='wss:'&&!(u.protocol==='ws:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error();const ws=new WebSocket(u);this.socket=ws;
 ws.onopen=()=>ws.send(JSON.stringify({type:'join',room:this.room,guestCharacter:Number(GUEST_DOOD_ID),character:this.room.startsWith('mock:')?this.mockCharacter:undefined}));
 ws.onmessage=event=>{try{const message=JSON.parse(String(event.data));if(message.type==='welcome'&&message.canAuthenticate&&this.authenticate&&typeof message.message==='string'&&message.message.startsWith('Doodverse multiplayer login\n')&&message.message.includes(`World: ${this.room}\n`)&&message.message.length<600){void this.authenticate(message.message).then(auth=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'authenticate',...auth}));}).catch(()=>{});return;}if(message.type!=='snapshot'||!Array.isArray(message.players))return;const keep=new Set<string>();for(const p of message.players.slice(0,24) as Pose[]){if(typeof p.id!=='string'||!Number.isInteger(p.character)||p.character<1||p.character>5000||![p.x,p.y,p.z,p.yaw].every(Number.isFinite)||!['Idle','Walk','Run','Jump'].includes(p.animation))continue;keep.add(p.id);let r=this.remotes.get(p.id);if(r&&r.pose.character!==p.character){r.avatar.dispose();this.remotes.delete(p.id);r=undefined;}if(!r){const camera=new PerspectiveCamera();camera.rotation.order='YXZ';camera.position.set(p.x,p.y,p.z);r={avatar:new PlayerAvatar(this.scene,BigInt(p.character)),camera,pose:p};this.remotes.set(p.id,r);}r.pose=p;}for(const [id,r]of this.remotes){if(!keep.has(id)){r.avatar.dispose();this.remotes.delete(id);}}this.status.textContent=`Multiplayer · ${this.remotes.size} nearby`; }catch{/* Discard malformed server payloads. */}};
 ws.onclose=()=>{this.clear();if(!this.disposed){this.status.textContent='Offline · solo play available · reconnecting';this.retry=setTimeout(()=>this.connect(),3000);}};ws.onerror=()=>ws.close();
 }catch{this.status.textContent='Multiplayer unavailable · solo play';}}
 update(anchor:PerspectiveCamera,dt:number,animation:Pose['animation']){this.elapsed+=dt;if(this.elapsed>=.1&&this.socket?.readyState===WebSocket.OPEN){this.elapsed=0;this.socket.send(JSON.stringify({type:'state',x:anchor.position.x,y:anchor.position.y,z:anchor.position.z,yaw:Math.atan2(Math.sin(anchor.rotation.y),Math.cos(anchor.rotation.y)),animation}));}
 for(const r of this.remotes.values()){const target=new Vector3(r.pose.x,r.pose.y,r.pose.z);r.camera.position.lerp(target,1-Math.exp(-dt*14));if(r.camera.position.distanceTo(target)>10)r.camera.position.copy(target);const diff=Math.atan2(Math.sin(r.pose.yaw-r.camera.rotation.y),Math.cos(r.pose.yaw-r.camera.rotation.y));r.camera.rotation.y+=diff*(1-Math.exp(-dt*14));r.avatar.update(r.camera,dt,r.pose.animation,10);}}
 useGuest(){this.mockCharacter=Number(GUEST_DOOD_ID);this.authenticate=undefined;if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({type:'guest'}));}
 private clear(){this.remotes.forEach(r=>r.avatar.dispose());this.remotes.clear();}
 dispose(){this.disposed=true;clearTimeout(this.retry);this.socket?.close();this.clear();this.status.remove();}
}
