import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,Contract,parseEther} from 'ethers';
import {compile} from '../scripts/compile-contracts.mjs';
compile();
const landArtifact=JSON.parse(fs.readFileSync('artifacts/Cloudacre.json','utf8'));
const seedArtifact=JSON.parse(fs.readFileSync('artifacts/Seed.json','utf8'));
async function fixture(){const rpc=ganache.provider({logging:{quiet:true},miner:{timestampIncrement:0},chain:{chainId:31337,hardfork:'shanghai'},wallet:{totalAccounts:4}});const provider=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});provider.pollingInterval=10;const alice=await provider.getSigner(0),bob=await provider.getSigner(1);const land=await new ContractFactory(landArtifact.abi,landArtifact.bytecode,alice).deploy('https://farm.example');await land.waitForDeployment();const seed=new Contract(await land.seed(),seedArtifact.abi,alice);await (await land.mint()).wait();return {rpc,provider,alice,bob,land,seed,close:()=>rpc.disconnect(),advance:async seconds=>{await rpc.request({method:'evm_increaseTime',params:[seconds]});await rpc.request({method:'evm_mine',params:[]})}}}
test('mint creates owned land with capped starter crops and prevents another faucet mint',async()=>{const f=await fixture();try{assert.equal(await f.land.ownerOf(1),await f.alice.getAddress());assert.equal(await f.land.pending(1),parseEther('20'));await assert.rejects(f.land.mint.staticCall());await assert.rejects(f.land.pending(999));assert.equal(await f.land.supportsInterface('0x49064906'),true)}finally{await f.close()}});
test('only the owner harvests; elapsed production caps and cannot be claimed twice',async()=>{const f=await fixture();try{await assert.rejects(f.land.connect(f.bob).harvest.staticCall(1));await (await f.land.harvest(1)).wait();assert.equal(await f.seed.balanceOf(await f.alice.getAddress()),parseEther('20'));await assert.rejects(f.land.harvest.staticCall(1));await f.advance(60);const n=await f.land.pending(1);assert.ok(n>=parseEther('6')&&n<parseEther('6.3'));await f.advance(10000);assert.equal(await f.land.pending(1),parseEther('20'));await (await f.land.harvest(1)).wait();assert.equal(await f.seed.balanceOf(await f.alice.getAddress()),parseEther('40'))}finally{await f.close()}});
test('upgrade burns SEED, settles old rate, and reverts without enough SEED',async()=>{const f=await fixture();try{await assert.rejects(f.land.upgrade.staticCall(1));assert.equal((await f.land.plots(1)).level,0n);await (await f.land.harvest(1)).wait();await f.advance(60);const receipt=await (await f.land.upgrade(1)).wait();assert.equal((await f.land.plots(1)).level,1n);assert.equal(await f.seed.balanceOf(await f.alice.getAddress()),0n);assert.equal(await f.seed.totalSupply(),0n);const stored=(await f.land.plots(1)).stored;assert.ok(stored>=parseEther('6')&&stored<parseEther('6.3'));assert.ok(receipt.logs.some(l=>{try{return f.land.interface.parseLog(l)?.name==='MetadataUpdate'}catch{return false}}));await f.advance(60);const n=await f.land.pending(1);assert.ok(n>=parseEther('18')&&n<parseEther('18.6'));await assert.rejects(f.land.upgrade.staticCall(1));assert.equal((await f.land.plots(1)).level,1n)}finally{await f.close()}});
test('upgrades and pending crops transfer with land, while harvested balances remain in the wallet',async()=>{const f=await fixture();try{await (await f.land.harvest(1)).wait();await (await f.land.upgrade(1)).wait();await f.advance(60);await (await f.land.harvest(1)).wait();const balance=await f.seed.balanceOf(await f.alice.getAddress());await f.advance(60);await (await f.land.transferFrom(await f.alice.getAddress(),await f.bob.getAddress(),1)).wait();assert.equal((await f.land.plots(1)).level,1n);assert.equal(await f.seed.balanceOf(await f.alice.getAddress()),balance);await assert.rejects(f.land.harvest.staticCall(1));await assert.rejects(f.land.upgrade.staticCall(1));await (await f.land.connect(f.bob).harvest(1)).wait();assert.ok(await f.seed.balanceOf(await f.bob.getAddress())>=parseEther('12'))}finally{await f.close()}});
test('approved NFT operators cannot spend owner rewards; SEED has no external mint/burn authority',async()=>{const f=await fixture();try{await (await f.land.approve(await f.bob.getAddress(),1)).wait();await assert.rejects(f.land.connect(f.bob).harvest.staticCall(1));await assert.rejects(f.land.connect(f.bob).upgrade.staticCall(1));await assert.rejects(f.seed.mint.staticCall(await f.alice.getAddress(),1));await assert.rejects(f.seed.spend.staticCall(await f.alice.getAddress(),1));await (await f.land.harvest(1)).wait();await (await f.seed.transfer(await f.bob.getAddress(),parseEther('5'))).wait();assert.equal(await f.seed.balanceOf(await f.bob.getAddress()),parseEther('5'))}finally{await f.close()}});
test('all three upgrades work and token metadata reflects the new level',async()=>{const f=await fixture();try{for(let level=0;level<3;level++){const cost=await f.land.upgradeCost(level);while(await f.seed.balanceOf(await f.alice.getAddress())<cost){await f.advance(1000);await (await f.land.harvest(1)).wait()}await (await f.land.upgrade(1)).wait();assert.equal((await f.land.plots(1)).level,BigInt(level+1))}await assert.rejects(f.land.upgrade.staticCall(1));await f.advance(10000);assert.equal(await f.land.pending(1),parseEther('160'));const uri=await f.land.tokenURI(1);const metadata=JSON.parse(Buffer.from(uri.split(',')[1],'base64').toString());assert.equal(metadata.attributes[0].value,4);assert.equal(metadata.attributes[1].value,48);assert.equal(metadata.animation_url,'https://farm.example/embed/?token=1');assert.equal(metadata.external_url,'https://farm.example/nft/?token=1');assert.match(metadata.image,/^data:image\/svg\+xml;base64,/)}finally{await f.close()}});

