import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,Contract,parseEther,zeroPadValue,toBeHex,ZeroHash} from 'ethers';
import {compile} from '../scripts/compile-contracts.mjs';
compile();
const artifact=name=>JSON.parse(fs.readFileSync(`artifacts/${name}.json`,'utf8'));
const random=n=>zeroPadValue(toBeHex(n),32);
async function fixture(size=0){
 const rpc=ganache.provider({logging:{quiet:true},miner:{timestampIncrement:0},chain:{chainId:31337,hardfork:'shanghai'},wallet:{totalAccounts:5}});
 const provider=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});provider.pollingInterval=10;
 const alice=await provider.getSigner(0),bob=await provider.getSigner(1),carol=await provider.getSigner(2);
 const deploy=async(name,args=[])=>{const a=artifact(name);const c=await new ContractFactory(a.abi,a.bytecode,alice).deploy(...args);await c.waitForDeployment();return c};
 const entropy=await deploy('TestEntropy');const field=await deploy('OilField',['https://oil.example',await entropy.getAddress()]);const oil=new Contract(await field.oil(),artifact('Oil').abi,alice);
 await (await field.mint(size)).wait();
 const survey=async(id=1,season=1,who=alice)=>{await (await field.connect(who).survey(id,season,ZeroHash,{value:await field.surveyFee(),gasLimit:400000})).wait();return (await field.reserves(id,season)).sequence};
 const reveal=async(seq,n)=>{return (await entropy.fulfill(seq,random(n),{gasLimit:200000})).wait()};
 return {rpc,provider,alice,bob,carol,entropy,field,oil,survey,reveal,close:()=>rpc.disconnect(),advance:async secs=>{await rpc.request({method:'evm_increaseTime',params:[secs]});await rpc.request({method:'evm_mine',params:[]})}};
}
test('oil parcels have immutable sizes, bounded supplies, and no starter oil',async()=>{const f=await fixture();try{assert.equal(await f.field.parcelSize(1),0n);assert.equal(await f.oil.totalSupply(),0n);assert.equal(await f.field.sizeSupply(0),500n);assert.equal(await f.field.sizeSupply(1),300n);assert.equal(await f.field.sizeSupply(2),200n);await assert.rejects(f.field.mint.staticCall(2));await assert.rejects(f.field.connect(f.bob).mint.staticCall(3));assert.equal(await f.field.currentSeason(),1n);assert.equal(await f.field.SEASON_DURATION(),604800n)}finally{await f.close()}});
test('survey requires owner, exact dynamic fee, and expected current season',async()=>{const f=await fixture();try{await assert.rejects(f.field.connect(f.bob).survey.staticCall(1,1,ZeroHash,{value:100}));await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:99}));await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:101}));await (await f.entropy.setFee(200)).wait();assert.equal(await f.field.surveyFee(),200n);await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:100}));assert.equal((await f.field.reserves(1,1)).requested,false);await f.advance(604800);await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:200}));await f.survey(1,2);assert.equal((await f.field.reserves(1,2)).requested,true)}finally{await f.close()}});
test('one request per parcel-season; only Pyth can reveal and duplicates cannot reroll',async()=>{const f=await fixture();try{const seq=await f.survey();await assert.rejects(f.field.survey.staticCall(1,1,random(88),{value:100}));assert.equal(await f.field.claimable(1,1),0n);await assert.rejects(f.field._entropyCallback.staticCall(seq,await f.entropy.defaultProvider(),random(999)));await (await f.entropy.deliver(await f.field.getAddress(),seq,await f.bob.getAddress(),random(999))).wait();assert.equal((await f.field.reserves(1,1)).fulfilled,false);const receipt=await f.reveal(seq,0);assert.ok(receipt.gasUsed<200000n);assert.equal((await f.field.reserves(1,1)).allocation,parseEther('1000'));await f.reveal(seq,999);assert.equal((await f.field.reserves(1,1)).allocation,parseEther('1000'));await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:100}));assert.equal(await f.oil.totalSupply(),0n)}finally{await f.close()}});
test('small, medium, and large allocations reach each bound without exceeding it',async()=>{const f=await fixture();try{await (await f.field.connect(f.bob).mint(1)).wait();await (await f.field.connect(f.carol).mint(2)).wait();for(const [id,size,signer] of [[1,0,f.alice],[2,1,f.bob],[3,2,f.carol]]){const [min,max]=await f.field.allocationBounds(size);await f.reveal(await f.survey(id,1,signer),max-min);assert.equal((await f.field.reserves(id,1)).allocation,max*10n**18n)}await f.advance(604800);for(const [id,size,signer] of [[1,0,f.alice],[2,1,f.bob],[3,2,f.carol]]){const [min]=await f.field.allocationBounds(size);await f.reveal(await f.survey(id,2,signer),0);assert.equal((await f.field.reserves(id,2)).allocation,min*10n**18n)}}finally{await f.close()}});
test('harvesting unlocks linearly, never exceeds allocation, and remains available after the season',async()=>{const f=await fixture();try{await f.reveal(await f.survey(),0);await assert.rejects(f.field.harvest.staticCall(1,1));await f.advance(302400);assert.equal(await f.field.claimable(1,1),parseEther('500'));await (await f.field.harvest(1,1)).wait();assert.equal(await f.oil.balanceOf(await f.alice.getAddress()),parseEther('500'));await assert.rejects(f.field.harvest.staticCall(1,1));await f.advance(604800);assert.equal(await f.field.claimable(1,1),parseEther('500'));await (await f.field.harvest(1,1)).wait();await assert.rejects(f.field.harvest.staticCall(1,1));assert.equal(await f.oil.totalSupply(),parseEther('1000'));await assert.rejects(f.oil.mint.staticCall(await f.alice.getAddress(),1))}finally{await f.close()}});
test('late callbacks resolve original seasons, independently of the next season request',async()=>{const f=await fixture(2);try{const old=await f.survey();await f.advance(604800);const next=await f.survey(1,2);await f.reveal(next,1);await f.reveal(old,0);assert.equal((await f.field.reserves(1,1)).allocation,parseEther('6000'));assert.equal((await f.field.reserves(1,2)).allocation,parseEther('6001'));assert.equal(await f.field.claimable(1,1),parseEther('6000'));assert.equal(await f.field.claimable(1,2),0n);await assert.rejects(f.field.survey.staticCall(1,1,ZeroHash,{value:100}))}finally{await f.close()}});
test('transfers preserve pending survey and allocation; only new owner can harvest',async()=>{const f=await fixture();try{const seq=await f.survey();await (await f.field.transferFrom(await f.alice.getAddress(),await f.bob.getAddress(),1)).wait();await f.reveal(seq,500);await assert.rejects(f.field.connect(f.bob).survey.staticCall(1,1,ZeroHash,{value:100}));await f.advance(604800);await assert.rejects(f.field.harvest.staticCall(1,1));await (await f.field.connect(f.bob).harvest(1,1)).wait();assert.equal(await f.oil.balanceOf(await f.bob.getAddress()),parseEther('1500'));assert.equal(await f.oil.balanceOf(await f.alice.getAddress()),0n);assert.equal(await f.field.parcelSize(1),0n)}finally{await f.close()}});
test('approved operators cannot farm; metadata uses oil routes and correct size',async()=>{const f=await fixture(1);try{await (await f.field.approve(await f.bob.getAddress(),1)).wait();await assert.rejects(f.field.connect(f.bob).survey.staticCall(1,1,ZeroHash,{value:100}));await assert.rejects(f.field.connect(f.bob).harvest.staticCall(1,1));const data=JSON.parse(Buffer.from((await f.field.tokenURI(1)).split(',')[1],'base64').toString());assert.equal(data.animation_url,'https://oil.example/oil/embed/?token=1');assert.equal(data.attributes[0].value,'Medium');assert.equal(await f.field.supportsInterface('0x49064906'),true);await assert.rejects(f.field.claimable(1,0));await assert.rejects(f.field.claimable(1,2));await assert.rejects(f.field.claimable(999,1))}finally{await f.close()}});

test('upgrades burn oil, checkpoint progress, preserve reserves and follow ownership',async()=>{const f=await fixture();try{
 await assert.rejects(f.field.upgrade.staticCall(1));assert.equal(await f.field.equipmentLevel(1),0n);
 await f.reveal(await f.survey(),0);await f.advance(302400);await (await f.field.harvest(1,1)).wait();
 await assert.rejects(f.oil.connect(f.bob).spend.staticCall(await f.alice.getAddress(),1));
 await assert.rejects(f.field.connect(f.bob).upgrade.staticCall(1));
 await (await f.field.upgrade(1)).wait();assert.equal(await f.oil.totalSupply(),parseEther('250'));assert.equal(await f.field.equipmentLevel(1),1n);assert.equal(await f.field.claimable(1,1),0n);
 await f.advance(60480);assert.equal(await f.field.claimable(1,1),parseEther('125'));
 await f.advance(604800);assert.equal(await f.field.claimable(1,1),parseEther('500'));
 await (await f.field.transferFrom(await f.alice.getAddress(),await f.bob.getAddress(),1)).wait();assert.equal(await f.field.equipmentLevel(1),1n);
 await assert.rejects(f.field.upgrade.staticCall(1));assert.equal((await f.field.reserves(1,1)).allocation,parseEther('1000'));
 }finally{await f.close()}});

test('upgrades during pending callbacks preserve work and cannot exceed maximum level',async()=>{const f=await fixture(2);try{
 await f.reveal(await f.survey(),4000);await f.advance(604800);await (await f.field.harvest(1,1)).wait();
 const seq=await f.survey(1,2);await f.advance(60480);await (await f.field.upgrade(1)).wait();await f.advance(60480);await f.reveal(seq,0);
 assert.equal(await f.field.claimable(1,2),parseEther('1350'));
 await (await f.field.upgrade(1)).wait();await assert.rejects(f.field.upgrade.staticCall(1));assert.equal(await f.field.equipmentLevel(1),2n);
 await f.advance(604800);await (await f.field.harvest(1,2)).wait();await (await f.field.upgrade(1)).wait();assert.equal(await f.field.equipmentLevel(1),3n);assert.equal(await f.field.upgradeCost(1),0n);await assert.rejects(f.field.upgrade.staticCall(1));
 }finally{await f.close()}});
