import * as THREE from 'three';
import {drums} from './drums.js';
const $=id=>document.getElementById(id),flashes=new Map(),buttons=new Map(),sources=new Set(),hatSources=new Set();let ctx,master,noise,enabled=false;
function error(e){$('status').textContent='Audio unavailable: '+e.message}
function enable(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=8;master.connect(compressor);compressor.connect(ctx.destination);noise=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const a=noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;}ctx.resume().catch(error);enabled=true;master.gain.setTargetAtTime(Number($('volume').value)/100*.7,ctx.currentTime,.01);$('power').textContent='Mute audio';$('power').setAttribute('aria-pressed','true');}
function track(s,g,filter,hat=false){sources.add(s);if(hat)hatSources.add(s);s.onended=()=>{sources.delete(s);hatSources.delete(s);s.disconnect();g.disconnect();filter?.disconnect()};if(sources.size>100){const old=sources.values().next().value;old.stop();sources.delete(old)}}
function tone(start,end,len,vol,type='sine',hat=false){const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(start,t);o.frequency.exponentialRampToValueAtTime(end,t+len);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+len);o.connect(g);g.connect(master);track(o,g,null,hat);o.start(t);o.stop(t+len+.03)}
function hiss(len,freq,vol,hat=false){const t=ctx.currentTime,s=ctx.createBufferSource(),g=ctx.createGain(),f=ctx.createBiquadFilter();s.buffer=noise;f.type='highpass';f.frequency.value=freq;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+len);s.connect(f);f.connect(g);g.connect(master);track(s,g,f,hat);s.start(t);s.stop(t+len+.03)}
function hit(id,open=false){try{enable();flashes.set(id,performance.now());$('status').textContent=(open&&id==='hat'?'Open hi-hat':drums.find(d=>d.id===id).name)+' · Live';if(id==='kick'){tone(150,42,.48,.8);hiss(.025,1600,.09)}else if(id==='snare'){tone(195,110,.16,.22,'triangle');hiss(.24,1200,.42)}else if(['tom1','tom2','floor'].includes(id)){const f={tom1:210,tom2:155,floor:105}[id];tone(f,f*.55,.48,.55);hiss(.04,1900,.07)}else if(id==='hat'){for(const s of hatSources)s.stop();hatSources.clear();hiss(open?.65:.08,7000,.19,true);tone(8100,8050,open?.4:.045,.025,'square',true)}else if(id==='crash'){hiss(2.5,2600,.3);[3400,4870,6310].forEach(f=>tone(f,f*.98,1.8,.027,'triangle'))}else{hiss(.8,6100,.11);[2600,4100,5700].forEach(f=>tone(f,f,.75,.04,'sine'))}}catch(e){error(e)}}
function stop(){for(const s of sources)s.stop();sources.clear();hatSources.clear();flashes.clear();$('status').textContent='All sounds stopped.'}
$('power').onclick=()=>{if(enabled){stop();enabled=false;master.gain.setTargetAtTime(0,ctx.currentTime,.01);$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false');}else{try{enable();$('status').textContent='Ready to play.'}catch(e){error(e)}}};$('stop').onclick=stop;$('volume').oninput=e=>{$('volumevalue').textContent=e.target.value+'%';if(ctx&&enabled)master.gain.setTargetAtTime(Number(e.target.value)/100*.7,ctx.currentTime,.02)};
drums.forEach(d=>{const b=document.createElement('button');b.className='pad';b.id='pad-'+d.id;b.innerHTML=d.name+'<span>'+d.key+'</span>';b.setAttribute('aria-label',d.name);b.onpointerdown=e=>{e.preventDefault();hit(d.id,e.shiftKey)};b.onclick=e=>{if(e.detail===0)hit(d.id,e.shiftKey)};$('pads').append(b);buttons.set(d.id,b)});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.altKey||e.metaKey||['INPUT','BUTTON'].includes(document.activeElement?.tagName))return;const d=drums.find(d=>d.key===e.key.toUpperCase());if(d){e.preventDefault();hit(d.id,e.shiftKey)}});window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();ctx?.suspend();enabled=false;$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false')}});
const canvas=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true})}catch(e){$('status').textContent='3D unavailable. Use the drum pads below.';$('cover').disabled=true}
const visuals=new Map();if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;scene.add(new THREE.HemisphereLight(0xcedbff,0x151221,3));const light=new THREE.DirectionalLight(0xffe2cd,4);light.position.set(-3,8,5);scene.add(light);const rim=new THREE.PointLight(0x8379ff,50);rim.position.set(3,4,-3);scene.add(rim);
const kit=new THREE.Group();scene.add(kit);const targets=[];const mat=(c,m=.3,r=.35)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});const shell=mat(0x8e302d,.6),chrome=mat(0xa5acb6,.9,.2),skin=mat(0xd5d5cb,.08,.55),gold=mat(0xc6a24f,.82,.33),rubber=mat(0x111622,.05,.8);
function cylinder(r,h,material,parent=kit){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,64),material);parent.add(m);return m}function rod(a,b,r=.035,material=chrome){const dir=new THREE.Vector3().subVectors(b,a);const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,dir.length(),12),material);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());kit.add(m);return m}const V=(x,y,z)=>new THREE.Vector3(x,y,z);
function stand(x,y,z){rod(V(x,.1,z),V(x,y,z));for(let j=0;j<3;j++){const a=j*Math.PI*2/3;rod(V(x,.35,z),V(x+Math.cos(a)*.45,.06,z+Math.sin(a)*.45))}}
function drum(id,x,y,z,r,depth,kick=false){const g=new THREE.Group();g.position.set(x,y,z);if(kick)g.rotation.x=Math.PI/2;kit.add(g);const body=cylinder(r,depth,shell,g);body.userData.id=id;targets.push(body);for(const side of [-1,1]){const head=cylinder(r*.98,.025,skin.clone(),g);head.position.y=side*depth/2;head.userData.id=id;targets.push(head);const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.035,10,64),chrome);ring.rotation.x=Math.PI/2;ring.position.y=side*(depth/2+.02);g.add(ring);for(let j=0;j<8;j++){const angle=j*Math.PI/4;const lug=new THREE.Mesh(new THREE.BoxGeometry(.055,.12,.055),chrome);lug.position.set(Math.cos(angle)*r,side*(depth/2-.08),Math.sin(angle)*r);g.add(lug)}if(side===1)visuals.set(id,{mesh:head,group:g,base:g.rotation.x,cymbal:false});}if(!kick)stand(x,y-depth/2,z);return g}
const kick=drum('kick',0,.92,.65,.87,.8,true);drum('snare',-1.25,1.03,1.05,.52,.3);drum('tom1',-.62,1.95,-.1,.45,.46);drum('tom2',.53,1.98,-.12,.52,.49);drum('floor',1.5,.95,.75,.65,.65);
function cymbal(id,x,y,z,r){stand(x,y,z);const g=new THREE.Group();g.position.set(x,y,z);kit.add(g);const disk=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.025,80),gold.clone());g.add(disk);const bell=new THREE.Mesh(new THREE.SphereGeometry(.17,24,12,0,Math.PI*2,0,Math.PI/2),gold);bell.scale.y=.5;g.add(bell);for(const m of [disk,bell]){m.userData.id=id;targets.push(m)}if(id==='hat'){const bottom=disk.clone();bottom.position.y=-.07;g.add(bottom);bottom.userData.id=id;targets.push(bottom)}for(let rad=.25;rad<r;rad+=.1){const groove=new THREE.Mesh(new THREE.TorusGeometry(rad,.002,4,80),chrome);groove.rotation.x=Math.PI/2;groove.position.y=.016;g.add(groove)}visuals.set(id,{mesh:disk,group:g,base:0,cymbal:true})}
cymbal('hat',-2.05,1.72,1,.48);cymbal('crash',-1.75,2.6,-.75,.83);cymbal('ride',1.9,2.4,-.67,.92);
const rug=new THREE.Mesh(new THREE.BoxGeometry(5.5,.045,4.2),mat(0x242332,.05,.9));rug.position.set(0,-.025,.1);kit.add(rug);const pedal=new THREE.Mesh(new THREE.BoxGeometry(.28,.06,.55),chrome);pedal.position.set(0,.045,1.5);kit.add(pedal);
const textureCanvas=document.createElement('canvas');textureCanvas.width=512;textureCanvas.height=512;const pen=textureCanvas.getContext('2d');pen.fillStyle='#d5d5cb';pen.fillRect(0,0,512,512);pen.fillStyle='#282c35';pen.textAlign='center';pen.font='bold 42px Arial';pen.fillText('BACKBEAT',256,245);pen.font='20px Arial';pen.fillText('CRYPTO DOODZ / 003',256,283);const texture=new THREE.CanvasTexture(textureCanvas);texture.colorSpace=THREE.SRGBColorSpace;const logo=new THREE.Mesh(new THREE.CircleGeometry(.82,64),new THREE.MeshStandardMaterial({map:texture,roughness:.65}));logo.position.set(0,.92,1.07);kit.add(logo);logo.userData.id='kick';targets.push(logo);
let yaw=0,pitch=.45,distance=8.8;function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();distance=Math.max(8.8,8/camera.aspect)}new ResizeObserver(resize).observe(canvas);$('reset').onclick=()=>{yaw=0;pitch=.45};const ray=new THREE.Raycaster(),p=new THREE.Vector2(),touches=new Map();function pick(e){const r=canvas.getBoundingClientRect();p.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(p,camera);return ray.intersectObjects(targets)[0]?.object.userData.id}canvas.onpointerdown=e=>{const id=pick(e);canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY,id});if(id)hit(id,e.shiftKey)};canvas.onpointermove=e=>{const t=touches.get(e.pointerId);if(!t)return;if(!t.id){yaw=Math.max(-1,Math.min(1,yaw-(e.clientX-t.x)*.006));pitch=Math.max(.15,Math.min(1.1,pitch+(e.clientY-t.y)*.006))}t.x=e.clientX;t.y=e.clientY};for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>touches.delete(e.pointerId));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function draw(now){camera.position.set(Math.sin(yaw)*distance,1+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,1.1,0);for(const [id,v]of visuals){const elapsed=(now-(flashes.get(id)??-10000))/1000;v.mesh.material.emissive.setHex(elapsed<.18?0x8a391c:0);v.mesh.material.emissiveIntensity=.6;v.group.rotation.x=v.base+(!reduced&&v.cymbal&&elapsed<1?Math.sin(elapsed*40)*Math.exp(-elapsed*5)*.06:0);}renderer.render(scene,camera);requestAnimationFrame(draw)}requestAnimationFrame(draw);
$('cover').onclick=()=>{const size=new THREE.Vector2();renderer.getSize(size);const ratio=renderer.getPixelRatio(),aspect=camera.aspect,pos=camera.position.clone();renderer.setPixelRatio(1);renderer.setSize(3000,3000,false);camera.aspect=1;camera.position.set(0,5.2,9);camera.lookAt(0,1.1,0);camera.updateProjectionMatrix();scene.background=new THREE.Color(0x0b0d12);renderer.render(scene,camera);const a=document.createElement('a');a.download='cryptodoodz-backbeat.png';a.href=canvas.toDataURL('image/png');a.click();scene.background=null;camera.aspect=aspect;camera.position.copy(pos);camera.updateProjectionMatrix();renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false)};
}
function animatePads(now){for(const [id,b]of buttons)b.classList.toggle('hit',now-(flashes.get(id)??-10000)<140);requestAnimationFrame(animatePads)}requestAnimationFrame(animatePads);
