import './style.css';

document.title='Doodverse — A world to make your own';
document.querySelector('#app')!.innerHTML=`
<div class="landing">
<nav aria-label="Main navigation"><a class="logo" href="./">◈ DOODVERSE</a><div><a href="#discover">Discover</a><a href="./mint.html">Mint assets ↗</a><a class="nav-enter" href="?mode=world">Enter world ↗</a></div></nav>
<main>
<section class="hero" aria-labelledby="hero-title">
<div class="hero-copy"><p class="eyebrow"><span class="dot"></span> ONE SHARED WORLD · BUILT ON BASE</p><h1 id="hero-title">Welcome to<br><em>Doodverse.</em></h1><p class="intro">Step into Doodverse as your CryptoDood. Meet a world of possibilities: build a home, display your art, and explore beyond your doorstep.</p><div class="actions"><a class="button primary" href="?mode=world">Enter the world <span>↗</span></a><a class="button secondary" href="./mint.html">Meet the collections <span>+</span></a></div><p class="entry-note">Choose your CryptoDood before entering. No Dood yet? Play as a free guest.</p></div>
<div class="hero-art"><span class="art-label">LIVE FROM PARCEL #1</span>
<iframe class="parcel-preview" src="?mode=showcase&tokenId=1&hero=1" title="Live view of Doodverse parcel 1. Drag to orbit." loading="lazy"></iframe><div class="art-caption"><span>5,000 parcels. One continuous world.</span><span>64 × 64 ↗</span></div><p class="illustration-note">Drag to orbit · <a href="?mode=world&tokenId=1">Visit parcel #1 ↗</a></p></div>
</section>
<section class="dood-feature"><div id="landing-dood"><picture><source media="(prefers-reduced-motion: reduce)" srcset="/art/cryptodoodz-reel.png"><img src="/art/cryptodoodz-reel.gif" alt="A selection of CryptoDoodz with different outfits, hair and accessories" width="420" height="420" loading="lazy"></picture></div><div><p class="eyebrow">5,000 CRYPTODOODZ · YOUR WORLD IDENTITY</p><h2>A world needs its Doodz.</h2><p>Your CryptoDood is more than something to display. Choose your wallet-owned character and take it exploring. Your NFT stays in your wallet.</p><a class="button primary" href="?mode=world">Choose your Dood ↗</a></div></section>
<section class="discover" id="discover" aria-labelledby="discover-title"><div class="section-heading"><p class="eyebrow">MORE THAN A COLLECTIBLE</p><h2 id="discover-title">Make yourself at home.</h2></div><div class="features"><article><span class="feature-number">01 / MINT</span><h3>Meet your Dood.</h3><p>Find your CryptoDood, claim a parcel, and pick up some trinkets. Make your start in Doodverse.</p></article><article><span class="feature-number">02 / BUILD</span><h3>Make it yours.</h3><p>Build a home, display your NFTs, and fill your space with treasures.</p></article><article><span class="feature-number">03 / EXPLORE</span><h3>Head out into the world.</h3><p>Take your Dood beyond your doorstep. Walk between parcels, step through portals, and discover what’s next.</p></article></div></section>
<section class="visit" aria-labelledby="visit-title"><div><p class="eyebrow">KNOW WHERE YOU’RE GOING?</p><h2 id="visit-title">Visit a parcel.</h2><p>Enter a parcel ID from 0 to 4,999 to jump into the world.</p></div><form action="" method="get"><input type="hidden" name="mode" value="world"><label for="visit-token">Parcel ID</label><div class="visit-input"><input id="visit-token" name="tokenId" type="number" min="0" max="4999" step="1" placeholder="e.g. 742" required><button class="button primary" type="submit">Visit ↗</button></div></form></section>
</main><footer><a class="logo" href="./">◈ DOODVERSE</a><span>An experimental world on Base. Built to be explored.</span><a href="./mint.html">Mint assets ↗</a></footer>
</div>`;
