import {privateKeyToAccount} from 'viem/accounts';
import {createServer} from 'node:http';
import test from 'node:test';
import assert from 'node:assert/strict';
import {WebSocket} from 'ws';
import {createPresenceServer} from './server.mjs';
const room='mock:8453:0x0000000000000000000000000000000000000000:7422026:2';
const pose={type:'state',x:100,y:3,z:100,yaw:0,animation:'Walk'};
async function connect(url,origin='http://127.0.0.1:5177'){const ws=new WebSocket(url,{origin});await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return ws;}
function message(ws,type){return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{ws.off('message',receive);reject(Error('timeout '+type));},2500);function receive(raw){const data=JSON.parse(raw);if(data.type===type){clearTimeout(timeout);ws.off('message',receive);resolve(data);}}ws.on('message',receive);});}
async function setup(t){const app=createPresenceServer();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());return `ws://127.0.0.1:${app.server.address().port}`;}
test('two clients see movement, nearby filtering, rooms and disconnect removal',async t=>{const url=await setup(t),a=await connect(url),b=await connect(url),c=await connect(url);for(const [ws,r]of [[a,room],[b,room],[c,room.replace('mock:','onchain:')]]){ws.send(JSON.stringify({type:'join',room:r}));await message(ws,'welcome');ws.send(JSON.stringify(pose));}let snap=await message(a,'snapshot');assert.equal(snap.players.length,1);assert.equal(snap.players[0].animation,'Walk');assert.equal(snap.players[0].character,12);b.send(JSON.stringify({...pose,x:1000}));snap=await message(a,'snapshot');assert.equal(snap.players.length,0);b.send(JSON.stringify(pose));await message(a,'snapshot');b.close();await new Promise(r=>b.once('close',r));snap=await message(a,'snapshot');assert.equal(snap.players.length,0);});
test('invalid origins and invalid coordinates are rejected',async t=>{const url=await setup(t);await assert.rejects(connect(url,'https://evil.example'));const ws=await connect(url);ws.send(JSON.stringify({type:'join',room}));await message(ws,'welcome');const closed=new Promise(r=>ws.once('close',r));ws.send(JSON.stringify({...pose,x:-1}));assert.equal(await closed,1008);});
test('character claims without authentication do not change guest appearance',async t=>{const url=await setup(t),a=await connect(url),b=await connect(url);for(const ws of [a,b]){ws.send(JSON.stringify({type:'join',room,character:77}));await message(ws,'welcome');ws.send(JSON.stringify({...pose,character:77}));}assert.equal((await message(a,'snapshot')).players[0].character,12);});

test('session authentication is single use and guest reset revokes appearance',async t=>{const app=createPresenceServer({characters:'configured',verifyIdentity:async(message,auth)=>message.includes('Nonce:')&&auth.signature==='valid'&&auth.character===77});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const url=`ws://127.0.0.1:${app.server.address().port}`,a=await connect(url),b=await connect(url);for(const ws of [a,b]){ws.send(JSON.stringify({type:'join',room:room.replace('mock:','onchain:')}));await message(ws,'welcome');ws.send(JSON.stringify(pose));}b.send(JSON.stringify({type:'authenticate',signature:'valid',character:77}));await message(b,'authenticated');assert.equal((await message(a,'snapshot')).players[0].character,77);b.send(JSON.stringify({type:'guest'}));assert.equal((await message(a,'snapshot')).players[0].character,12);});

test('mock opt-in shares each selected character in both directions but never trusts onchain claims',async t=>{const app=createPresenceServer({allowMockAvatars:true});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const url=`ws://127.0.0.1:${app.server.address().port}`,a=await connect(url),b=await connect(url);for(const [ws,character]of [[a,2],[b,77]]){ws.send(JSON.stringify({type:'join',room,character}));await message(ws,'welcome');ws.send(JSON.stringify(pose));}assert.equal((await message(a,'snapshot')).players[0].character,77);assert.equal((await message(b,'snapshot')).players[0].character,2);b.send(JSON.stringify({type:'guest'}));assert.equal((await message(a,'snapshot')).players[0].character,12);const c=await connect(url),d=await connect(url);for(const ws of [c,d]){ws.send(JSON.stringify({type:'join',room:room.replace('mock:','onchain:'),character:77}));await message(ws,'welcome');ws.send(JSON.stringify(pose));}assert.equal((await message(c,'snapshot')).players[0].character,12);});

test('random guest appearance is shared and restored after guest reset',async t=>{const url=await setup(t),a=await connect(url),b=await connect(url);for(const [ws,id]of [[a,1],[b,5000]]){ws.send(JSON.stringify({type:'join',room,guestCharacter:id}));await message(ws,'welcome');ws.send(JSON.stringify(pose));}assert.equal((await message(a,'snapshot')).players[0].character,5000);assert.equal((await message(b,'snapshot')).players[0].character,1);b.send(JSON.stringify({type:'guest'}));assert.equal((await message(a,'snapshot')).players[0].character,5000);});

async function sessionSetup(t,sessionTTL=60000){let owned=true,checks=0;const app=createPresenceServer({characters:'configured',sessionTTL,verifyIdentity:async(_,auth)=>{checks++;return owned&&auth.signature==='valid'&&auth.character===77;}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const url=`ws://127.0.0.1:${app.server.address().port}`;async function join(r=room.replace('mock:','onchain:')){const ws=await connect(url);ws.send(JSON.stringify({type:'join',room:r}));await message(ws,'welcome');return ws;}const first=await join();first.send(JSON.stringify({type:'authenticate',signature:'valid',character:77}));const {resumeToken}=await message(first,'authenticated');assert.equal(typeof resumeToken,'string');return {join,first,resumeToken,revoke:()=>owned=false,checks:()=>checks};}
test('reconnect resumes signed identity without another signature and still checks ownership',async t=>{const s=await sessionSetup(t);s.first.close();const ws=await s.join();ws.send(JSON.stringify({type:'resume',token:s.resumeToken}));assert.equal((await message(ws,'authenticated')).resumeToken,s.resumeToken);assert.equal(s.checks(),2);s.revoke();const next=await s.join();next.send(JSON.stringify({type:'resume',token:s.resumeToken}));await message(next,'authFailed');});
test('resume is room-bound, rejects unknown tokens and guest reset revokes token',async t=>{const s=await sessionSetup(t);const wrong=await s.join(room.replace('mock:','onchain:').replace(':7422026:',':99:'));wrong.send(JSON.stringify({type:'resume',token:s.resumeToken}));await message(wrong,'authFailed');const ws=await s.join();ws.send(JSON.stringify({type:'resume',token:'unknown'}));await message(ws,'authFailed');s.first.send(JSON.stringify({type:'guest'}));s.first.send(JSON.stringify(pose));await message(s.first,'snapshot');ws.send(JSON.stringify({type:'resume',token:s.resumeToken}));await message(ws,'authFailed');});
test('expired resume tokens cannot authenticate',async t=>{const s=await sessionSetup(t,-1);const ws=await s.join();ws.send(JSON.stringify({type:'resume',token:s.resumeToken}));await message(ws,'authFailed');});

test('production character authentication accepts only the latest collection despite obsolete environment values',async t=>{
 const latest='0x16E9432a0a09c903e70ca8467Ce3bfE77b3Dc56f',original='0x03847D61A017731A843109F0b6BC637AF8a3f7e0';
 const account=privateKeyToAccount('0x'+'12'.repeat(32));let calls=0;
 const rpc=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const q=JSON.parse(body);calls++;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:q.id,result:q.method==='eth_chainId'?'0x2105':'0x'+account.address.slice(2).toLowerCase().padStart(64,'0')}));});
 await new Promise(r=>rpc.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>rpc.close(r)));
 const old=process.env.CHARACTER_ADDRESS,oldList=process.env.CHARACTER_ADDRESSES;process.env.CHARACTER_ADDRESS=original;process.env.CHARACTER_ADDRESSES=original;
 const app=createPresenceServer({rpc:`http://127.0.0.1:${rpc.address().port}`});
 if(old===undefined)delete process.env.CHARACTER_ADDRESS;else process.env.CHARACTER_ADDRESS=old;
 if(oldList===undefined)delete process.env.CHARACTER_ADDRESSES;else process.env.CHARACTER_ADDRESSES=oldList;
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());
 for(const collection of [original,latest]){
  const ws=await connect(`ws://127.0.0.1:${app.server.address().port}`);ws.send(JSON.stringify({type:'join',room:room.replace('mock:','onchain:')}));const welcome=await message(ws,'welcome');
  const signature=await account.signMessage({message:welcome.message});ws.send(JSON.stringify({type:'authenticate',address:account.address,character:1,collection,signature}));
  await message(ws,collection===original?'authFailed':'authenticated');
  if(collection===original)assert.equal(calls,0);else assert.ok(calls>=2);ws.close();
 }
});
