import * as THREE from 'three';
import {xyloNotes,bongoPads} from './notes.js';
export function startInstrument(item){
const xylo=item===4,$=id=>document.getElementById(id),pads=xylo?xyloNotes:bongoPads,buttons=new Map(),flashes=new Map(),sources=new Set();let ctx,master,noise,enabled=false;
const keyMap=xylo?['a','w','s','e','d','f','t','g','y','h','u','j','k']:['a','s','d','j','k','l'];
function fail(e){$('status').textContent='Audio unavailable: '+e.message}
function enable(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();const limit=ctx.createDynamicsCompressor();limit.threshold.value=-18;limit.ratio.value=8;master.connect(limit);limit.connect(ctx.destination);noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const a=noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;}ctx.resume().catch(fail);enabled=true;master.gain.setTargetAtTime(Number($('volume').value)/100*.65,ctx.currentTime,.01);$('power').textContent='Mute audio';$('power').setAttribute('aria-pressed','true');}
function sound(freq,end,len,volume,type='sine'){const t=ctx.currentTime,g=ctx.createGain(),o=type==='noise'?ctx.createBufferSource():ctx.createOscillator();if(type==='noise')o.buffer=noise;else{o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(end,t+len);}g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.002);g.gain.exponentialRampToValueAtTime(.0001,t+len);o.connect(g);g.connect(master);sources.add(o);o.onended=()=>{sources.delete(o);o.disconnect();g.disconnect()};o.start(t);o.stop(t+len+.02);if(sources.size>120){const old=sources.values().next().value;old.stop();sources.delete(old)}}
function hit(id){const pad=pads.find(p=>p.id===id);if(!pad)return;try{enable();flashes.set(xylo?id:pad.drum,performance.now());flashes.set(id,performance.now());$('status').textContent=pad.name+' · Live';if(xylo){const f=440*2**((pad.note-69)/12);sound(f,f,.85,.32);sound(f*3,f*3,.28,.055);sound(f*6,f*6,.09,.015);sound(0,0,.015,.025,'noise')}else{const f=pad.drum==='small'?290:195;const slap=pad.stroke==='slap',rim=pad.stroke==='rim';sound(f*(rim?2:1.35),f*(rim?1.8:1),rim?.09:slap?.16:.34,slap?.36:.42);sound(f*1.6,f*1.5,.12,.08);sound(0,0,slap?.095:rim?.02:.035,slap?.28:rim?.1:.065,'noise')}}catch(e){fail(e)}}
function stop(){for(const o of sources)o.stop();sources.clear();flashes.clear();$('status').textContent='All sounds stopped.'}
$('stop').onclick=stop;$('power').onclick=()=>{if(enabled){stop();master.gain.setTargetAtTime(0,ctx.currentTime,.01);enabled=false;$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false')}else{try{enable();$('status').textContent='Ready to play.'}catch(e){fail(e)}}};$('volume').oninput=e=>{$('volumevalue').textContent=e.target.value+'%';if(enabled)master.gain.setTargetAtTime(Number(e.target.value)/100*.65,ctx.currentTime,.02)};
pads.forEach((p,i)=>{const b=document.createElement('button');b.className='pad';b.setAttribute('aria-label',p.name);b.textContent=p.name;const hint=document.createElement('span');hint.textContent=keyMap[i]?.toUpperCase()||'TOUCH';b.append(hint);b.onpointerdown=e=>{e.preventDefault();hit(p.id)};b.onclick=e=>{if(e.detail===0)hit(p.id)};$('pads').append(b);buttons.set(p.id,b)});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||['INPUT','BUTTON','SELECT'].includes(document.activeElement?.tagName))return;const i=keyMap.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();hit(pads[i].id)}});window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();ctx?.suspend();enabled=false;$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false')}});
const canvas=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true})}catch(e){$('status').textContent='3D unavailable. Use the pads below.';$('cover').disabled=true}
if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;scene.add(new THREE.HemisphereLight(0xe1eaff,0x21182c,3));const light=new THREE.DirectionalLight(0xffecd3,4);light.position.set(-3,7,4);scene.add(light);const rim=new THREE.PointLight(0x8a85ff,40);rim.position.set(4,4,-3);scene.add(rim);const root=new THREE.Group();scene.add(root);const targets=[],visuals=new Map();const mat=(color,metalness=.2,roughness=.4)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const wood=mat(0x502b1b,.05,.55),chrome=mat(0xb9a781,.8,.24),dark=mat(0x121722,.1,.7);
function box(w,h,d,x,y,z,m){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);root.add(mesh);return mesh}function cylinder(r1,r2,h,x,y,z,m){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,64),m);mesh.position.set(x,y,z);root.add(mesh);return mesh}
if(xylo){box(10,.35,3.5,0,0,0,wood);box(9.8,.05,3.4,0,.2,0,dark);for(const x of [-4.3,4.3])for(const z of [-1.3,1.3])box(.25,.6,.25,x,-.42,z,chrome);let white=0;for(const p of xyloNotes){const index=p.black?white-.5:white++;const x=(index-7)*.6,len=1.75-(p.note-60)*.035,z=p.black?-.87:.65;const color=new THREE.Color().setHSL((p.note-60)/30,.65,p.black?.32:.48);const b=box(p.black?.43:.51,.19,len,x,p.black?.6:.39,z,mat(color,.25,.35));b.userData.id=p.id;targets.push(b);visuals.set(p.id,b);for(const dz of [-len*.34,len*.34])cylinder(.035,.035,.018,x,p.black?.705:.495,z+dz,chrome);const tube=cylinder(.105,.105,.65+(84-p.note)*.025,x,-.54,z,chrome);tube.userData.decorative=true;}
// Two mallets resting alongside the instrument.
for(const x of [-4.7,4.7]){const shaft=box(.045,.045,2,x,.34,0,chrome);shaft.rotation.y=x>0?.12:-.12;const head=new THREE.Mesh(new THREE.SphereGeometry(.14,24,16),mat(0xeed7aa,.02,.7));head.position.set(x,.4,-1.03);root.add(head)}
}else{box(1.1,.3,.4,0,.4,0,wood);for(const [drum,x,r,h]of [['small',-.95,.78,1.5],['large',.98,1,1.8]]){const shell=cylinder(r*.95,r*.68,h,x,0,0,mat(drum==='small'?0xb76329:0x8c3d24,.15,.4));shell.userData.id=drum;targets.push(shell);for(const y of [-h/2+.14,h/2-.1]){const ring=new THREE.Mesh(new THREE.TorusGeometry(y>0?r*.96:r*.72,.055,12,64),chrome);ring.rotation.x=Math.PI/2;ring.position.set(x,y,0);root.add(ring)}const skin=cylinder(r,r,.045,x,h/2+.01,0,mat(0xe4c999,.03,.78));skin.userData.id=drum;targets.push(skin);visuals.set(drum,skin);for(let j=0;j<8;j++){const a=j*Math.PI/4;const lug=box(.055,h*.73,.055,x+Math.cos(a)*r*.87,0,Math.sin(a)*r*.87,chrome);lug.rotation.z=-Math.cos(a)*.13;lug.rotation.x=Math.sin(a)*.13;}cylinder(r*.72,r*.72,.08,x,-h/2,0,dark);}}
let yaw=0,pitch=xylo?.7:.68,distance=xylo?13:7;function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();distance=Math.max(xylo?13:7,(xylo?15:7)/camera.aspect)}new ResizeObserver(resize).observe(canvas);$('reset').onclick=()=>{yaw=0;pitch=xylo?.7:.68};const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),touches=new Map();function pick(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(pointer,camera);return ray.intersectObjects(targets)[0]?.object.userData.id}canvas.onpointerdown=e=>{const id=pick(e);canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{id,x:e.clientX,y:e.clientY});if(id)hit(xylo?id:id+'-'+$('stroke').value)};canvas.onpointermove=e=>{const t=touches.get(e.pointerId);if(!t)return;if(!t.id){yaw=Math.max(-1.2,Math.min(1.2,yaw-(e.clientX-t.x)*.006));pitch=Math.max(.2,Math.min(1.3,pitch+(e.clientY-t.y)*.006))}else if(xylo){const id=pick(e);if(id&&id!==t.id){hit(id);t.id=id}}t.x=e.clientX;t.y=e.clientY};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>touches.delete(e.pointerId));
function draw(now){camera.position.set(Math.sin(yaw)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,0,0);for(const [id,m]of visuals){m.material.emissive.setHex(now-(flashes.get(id)??-10000)<160?0x8b5732:0);m.material.emissiveIntensity=.7;}renderer.render(scene,camera);requestAnimationFrame(draw)}requestAnimationFrame(draw);
$('cover').onclick=()=>{const size=new THREE.Vector2();renderer.getSize(size);const ratio=renderer.getPixelRatio(),aspect=camera.aspect,pos=camera.position.clone();renderer.setPixelRatio(1);renderer.setSize(3000,3000,false);camera.aspect=1;camera.position.set(0,xylo?13:5,xylo?14:6);camera.lookAt(0,0,0);camera.updateProjectionMatrix();scene.background=new THREE.Color(0x0b0d12);renderer.render(scene,camera);const a=document.createElement('a');a.download=xylo?'cryptodoodz-prism.png':'cryptodoodz-barrio.png';a.href=canvas.toDataURL('image/png');a.click();scene.background=null;camera.aspect=aspect;camera.position.copy(pos);camera.updateProjectionMatrix();renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false)};
}
function animate(now){for(const [id,b]of buttons)b.classList.toggle('hit',now-(flashes.get(id)??-10000)<150);requestAnimationFrame(animate)}requestAnimationFrame(animate);
}
