import * as THREE from 'three';
import {makeKeys,frequency,noteName} from './notes.js';
const $=id=>document.getElementById(id),keys=makeKeys(),held=new Map(),voices=new Map(),buttons=new Map(),meshes=new Map();
let ctx,master,muted=false,sustainLatch=false,sustainHeld=false,octave=4;
const sustain=()=>sustainLatch||sustainHeld;
function ensureAudio(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();master.gain.value=Number($('volume').value)/100*.65;const limit=ctx.createDynamicsCompressor();limit.threshold.value=-18;limit.ratio.value=8;master.connect(limit);limit.connect(ctx.destination);}if(ctx.state!=='running')ctx.resume().catch(error);muted=false;master.gain.setTargetAtTime(Number($('volume').value)/100*.65,ctx.currentTime,.02);$('power').textContent='Mute audio';$('power').setAttribute('aria-pressed','true');}
function error(e){$('status').textContent='Audio unavailable: '+e.message;}
function release(note,immediate=false){const v=voices.get(note);if(!v)return;voices.delete(note);const t=ctx.currentTime;v.g.gain.cancelAndHoldAtTime(t);v.g.gain.setTargetAtTime(.00001,t,immediate?.015:.15);v.oscs.forEach(o=>o.stop(t+(immediate?.08:1)));}
function synth(note){release(note,true);if(voices.size>=40)release(voices.keys().next().value,true);const t=ctx.currentTime,g=ctx.createGain(),voice=$('voice').value;g.connect(master);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.18,t+.008);if(voice!=='organ')g.gain.exponentialRampToValueAtTime(.008,t+(voice==='piano'?2.8:4));const oscs=[1,2,3].map((harmonic,i)=>{const o=ctx.createOscillator(),level=ctx.createGain();o.type=voice==='electric'&&i===0?'triangle':'sine';o.frequency.value=frequency(note)*harmonic;level.gain.value=[1,.22,.07][i];o.connect(level);level.connect(g);o.start(t);o.onended=()=>{o.disconnect();level.disconnect();if(i===0)g.disconnect()};return o});voices.set(note,{g,oscs});}
function highlight(){const active=new Set(held.values());for(const [n,b]of buttons)b.classList.toggle('active',active.has(n));$('note').textContent=active.size?[...active].sort((a,b)=>a-b).map(noteName).join(' · '):'Ready';}
function down(source,note){if(held.get(source)===note)return;up(source);try{ensureAudio();const already=[...held.values()].includes(note);held.set(source,note);if(!already)synth(note);highlight();$('status').textContent='Playing · '+noteName(note);}catch(e){error(e)}}
function up(source){const note=held.get(source);held.delete(source);if(note!==undefined&&![...held.values()].includes(note)&&!sustain())release(note);highlight();}
function updateSustain(){const on=sustain();$('sustain').textContent=on?'Sustain on':'Sustain off';$('sustain').setAttribute('aria-pressed',String(on));if(!on)for(const note of voices.keys())if(![...held.values()].includes(note))release(note);}
function panic(){held.clear();for(const note of voices.keys())release(note,true);sustainHeld=false;updateSustain();highlight();$('status').textContent='All notes released.';}
$('power').onclick=()=>{try{if(!ctx||muted){ensureAudio();$('status').textContent='Ready to play.';}else{panic();muted=true;master.gain.setTargetAtTime(0,ctx.currentTime,.015);$('power').textContent='Enable audio';$('power').setAttribute('aria-pressed','false');}}catch(e){error(e)}};
$('stop').onclick=panic;$('sustain').onclick=()=>{sustainLatch=!sustainLatch;updateSustain()};$('voice').onchange=panic;$('volume').oninput=e=>{$('volumevalue').textContent=e.target.value+'%';if(ctx&&!muted)master.gain.setTargetAtTime(Number(e.target.value)/100*.65,ctx.currentTime,.02)};
keys.forEach(k=>{const b=document.createElement('button');b.className='key '+(k.black?'black':'white');b.style.left=(k.x*36+(k.black?6:0))+'px';b.dataset.note=k.note;b.setAttribute('aria-label',k.name);b.textContent=k.black?'':k.name;b.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();if(!e.repeat)down('button'+k.note,k.note)}};b.onkeyup=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();up('button'+k.note)}};b.onblur=()=>up('button'+k.note);$('keys').append(b);buttons.set(k.note,b)});
const pointers=new Set();function pointerNote(e){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-note]');return el&&el.classList.contains('key')?Number(el.dataset.note):null;}
$('keys').onpointerdown=e=>{const n=pointerNote(e);if(n===null)return;e.preventDefault();pointers.add(e.pointerId);$('keys').setPointerCapture(e.pointerId);down('touch'+e.pointerId,n)};
$('keys').onpointermove=e=>{if(!pointers.has(e.pointerId))return;const n=pointerNote(e);if(n===null)up('touch'+e.pointerId);else down('touch'+e.pointerId,n)};
for(const type of ['pointerup','pointercancel','lostpointercapture'])$('keys').addEventListener(type,e=>{pointers.delete(e.pointerId);up('touch'+e.pointerId)});
function jump(n){const k=keys.find(k=>k.note===n);$('keyscroll').scrollLeft=Math.max(0,k.x*36-45)}document.querySelectorAll('.rangenav button').forEach(b=>b.onclick=()=>jump(Number(b.dataset.note)));jump(60);
const typing=['a','w','s','e','d','f','t','g','y','h','u','j','k'];document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement?.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const key=e.key.toLowerCase();if(key===' '){e.preventDefault();sustainHeld=true;updateSustain();return}if(key==='z'||key==='x'){octave=Math.max(1,Math.min(7,octave+(key==='x'?1:-1)));$('octave').textContent='Typing octave '+octave;return}const i=typing.indexOf(key);if(i>=0){e.preventDefault();down('type'+key,(octave+1)*12+i)}});document.addEventListener('keyup',e=>{up('type'+e.key.toLowerCase());if(e.code==='Space'){sustainHeld=false;updateSustain()}});window.addEventListener('blur',panic);document.addEventListener('visibilitychange',()=>{if(document.hidden){panic();ctx?.suspend()}});
const canvas=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});}catch(e){$('status').textContent='3D unavailable. Play using the keys below.';$('cover').disabled=true;}
if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;scene.add(new THREE.HemisphereLight(0xdce6ff,0x151720,3));const light=new THREE.DirectionalLight(0xffead4,4);light.position.set(2,7,4);scene.add(light);const rim=new THREE.PointLight(0x81aaff,50);rim.position.set(-3,4,-3);scene.add(rim);
const board=new THREE.Group();scene.add(board);const material=(color,metalness=.2,roughness=.35)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const dark=material(0x171d28,.65),gold=material(0xc7a36a,.8),wood=material(0x3a241c,.2,.6);
function box(w,h,d,x,y,z,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);board.add(m);return m}box(16.6,.5,3.2,0,0,0,dark);box(16.7,.08,3.23,0,-.2,0,gold);box(.24,.62,3.2,-8.4,.02,0,wood);box(.24,.62,3.2,8.4,.02,0,wood);box(16.2,.09,.06,0,.29,-.36,gold);
const hitKeys=[];keys.forEach(k=>{const x=(k.x-25.5)*.31,m=box(k.black?.19:.299,k.black?.22:.13,k.black?1.02:1.8,x,k.black?.48:.30,k.black?.19:.55,material(k.black?0x080c13:0xf1eee4,k.black?.25:.1));m.userData.note=k.note;m.userData.baseY=m.position.y;hitKeys.push(m);meshes.set(k.note,m)});
function label(text,x,z,width){const c=document.createElement('canvas');c.width=1024;c.height=128;const g=c.getContext('2d');g.fillStyle='#debf8a';g.font='500 58px Arial';g.textAlign='center';g.fillText(text,512,84);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,width/8),new THREE.MeshBasicMaterial({map:texture,transparent:true}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.27,z);board.add(mesh)}label('N O C T U R N E   8 8',0,-1.03,4);label('CRYPTO DOODZ / 002',5.8,-1.02,2.8);
for(let j=0;j<3;j++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.115,.115,.12,24),gold);m.position.set(-7+j*.42,.3,-1);board.add(m)}
let yaw=0,pitch=.8,distance=19;function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;distance=Math.max(19,29/camera.aspect);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);$('reset').onclick=()=>{yaw=0;pitch=.8};const ray=new THREE.Raycaster(),v=new THREE.Vector2(),touches=new Map();function pick(e){const r=canvas.getBoundingClientRect();v.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(v,camera);return ray.intersectObjects(hitKeys)[0]?.object.userData.note;}
canvas.onpointerdown=e=>{const n=pick(e);canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY,play:n!==undefined});if(n!==undefined)down('scene'+e.pointerId,n)};canvas.onpointermove=e=>{const t=touches.get(e.pointerId);if(!t)return;if(t.play){const n=pick(e);if(n===undefined)up('scene'+e.pointerId);else down('scene'+e.pointerId,n)}else{yaw=Math.max(-.65,Math.min(.65,yaw-(e.clientX-t.x)*.005));pitch=Math.max(.4,Math.min(1.3,pitch+(e.clientY-t.y)*.005))}t.x=e.clientX;t.y=e.clientY};for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{touches.delete(e.pointerId);up('scene'+e.pointerId)});
function draw(){camera.position.set(Math.sin(yaw)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,0,0);const active=new Set(held.values());for(const [n,m]of meshes){m.position.y=m.userData.baseY-(active.has(n)?.07:0);m.material.emissive.setHex(active.has(n)?0x7c5017:0);m.material.emissiveIntensity=.7}renderer.render(scene,camera);requestAnimationFrame(draw)}requestAnimationFrame(draw);
$('cover').onclick=()=>{const size=new THREE.Vector2();renderer.getSize(size);const ratio=renderer.getPixelRatio(),aspect=camera.aspect,pos=camera.position.clone();renderer.setPixelRatio(1);renderer.setSize(3000,3000,false);camera.aspect=1;camera.position.set(0,18,22);camera.lookAt(0,0,0);camera.updateProjectionMatrix();scene.background=new THREE.Color(0x0b0d12);renderer.render(scene,camera);const a=document.createElement('a');a.download='cryptodoodz-nocturne88.png';a.href=canvas.toDataURL();a.click();scene.background=null;camera.aspect=aspect;camera.position.copy(pos);camera.updateProjectionMatrix();renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false)};
}
