import test from 'node:test';
import assert from 'node:assert/strict';
import { MockInventoryProvider } from '../src/items/mockInventory.ts';
import { MockParcelStateProvider } from '../src/blockchain/mockParcelState.ts';

test('attached items follow parcel ownership across persistence and pickup', async () => {
  const alice = '0x1111111111111111111111111111111111111111' as const;
  const bob = '0x2222222222222222222222222222222222222222' as const;
  let account: typeof alice | typeof bob = alice;
  let owner: typeof alice | typeof bob = alice;
  const data = new Map<string, string>();
  const storage = { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => { data.set(key, value); } };
  const create = () => new MockInventoryProvider(storage, () => account, id => id === 742 && account === owner);
  let provider = create();
  const buildings = new MockParcelStateProvider(storage, id => id === 742 && account === owner);
  await buildings.addObject(742n, { objectType: 1, x: 3200, z: 3200, rotation: 0 });
  await provider.placePortal(742, { destinationTokenId: 743, x: 3200, z: 3200, rotation: 0 });
  await provider.grantDevItem(3, 19n);
  await provider.grantDevItem(2, 23n);
  await provider.placeItem(742, { itemType: 3, quantity: 12n, x: 3200, z: 3200, rotation: 0 });
  assert.equal(await provider.getBalance(alice, 3n), 7n);
  const originalObjects = await buildings.getObjects(742n);
  const originalPortals = await provider.getPortals(742);
  owner = bob;
  provider = create();
  const [item] = await provider.getItems(742);
  assert.equal(item.depositor, alice);
  assert.deepEqual(await buildings.getObjects(742n), originalObjects);
  assert.deepEqual(await provider.getPortals(742), originalPortals);
  await assert.rejects(buildings.removeObject(742n, 1), /owner/);
  await assert.rejects(provider.removePortal(742, 1), /owner/);
  await assert.rejects(provider.pickupItem(742, item.id), /current parcel owner/);
  await assert.rejects(provider.evictItem(742, item.id), /current parcel owner/);
  account = bob;
  await buildings.removeObject(742n, 1);
  await provider.removePortal(742, 1);
  await provider.pickupItem(742, item.id);
  assert.equal(await provider.getBalance(bob, 3n), 12n);
  assert.equal(await provider.getBalance(alice, 3n), 7n);
  assert.equal(await provider.getBalance(alice, 2n), 23n);
  assert.deepEqual(await create().getItems(742), []);
  await assert.rejects(provider.pickupItem(742, item.id), /no longer exists/);
  assert.equal(await provider.getBalance(bob, 3n), 12n);
});
