import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { assetKey, parseAssetKey, evaluateAccess, type NFTStateProvider } from '../src/nfts/model.ts';
import { MockNFTProvider, MOCK_NFT_ESCROW, MOCK_ITEMS } from '../src/nfts/mock.ts';
import { MockInventoryProvider } from '../src/items/mockInventory.ts';
import { MetadataCache, loadMetadata, parseMetadata, resolveURL } from '../src/nfts/metadata.ts';
import { NFTLayer, NFTRepresentationRegistry } from '../src/nfts/rendering.ts';
const alice = '0x1111111111111111111111111111111111111111' as const, bob = '0x2222222222222222222222222222222222222222' as const;
function setup() { let account: string = alice, owner: string = alice; const map = new Map<string, string>(); const storage = { getItem: (k: string) => map.get(k) ?? null, setItem: (k: string, v: string) => { map.set(k, v); } }; const ledger = new MockInventoryProvider(storage, () => account as typeof alice, id => [742, 743].includes(id) && account === owner); const create = () => new MockNFTProvider(ledger, 31337, alice, id => [742, 743].includes(id) && account === owner); return { ledger, create, map, storage, account: (v: string) => { account = v; }, sell: () => { owner = bob; } }; }
const floor = { kind: 'parcel' as const, parcelId: 742, x: 3200, z: 3200, rotation: 0 };
test('asset identity roundtrips bigint and rejects malformed/cross-chain identities', () => { const key = assetKey({ chainId: 31337, contractAddress: alice, tokenId: 2n ** 200n }); assert.equal(assetKey(parseAssetKey(key)), key); for (const bad of ['abc', '1:javascript:1', '1:' + alice + ':-1'])
    assert.throws(() => parseAssetKey(bad)); assert.throws(() => assetKey({ chainId: 1, contractAddress: alice, tokenId: 1n << 256n })); });
test('wallet → parcel → container → parcel → wallet, sale inheritance and no duplication', async () => { const s = setup(), p = s.create(), asset = p.knownAssets()[0]; await p.attach(asset, floor); assert.equal(await p.ownerOf(asset), MOCK_NFT_ESCROW); await assert.rejects(p.attach(asset, floor)); await p.createContainer(742, floor, 2); await p.move(asset, { kind: 'container', parcelId: 742, containerId: 1 }); assert.equal((await p.snapshot(742)).attachments.length, 1); await s.ledger.grantDevItem(3, 20n); await p.storeItem(1, 3, 12n); assert.equal(await s.ledger.getBalance(alice, 3n), 8n); await assert.rejects(p.removeContainer(1), /contains 2/); const before = await p.snapshot(742); s.sell(); assert.deepEqual(await s.create().snapshot(742), before); await assert.rejects(p.detach(asset), /current parcel owner/); await assert.rejects(p.retrieveItem(1, 3, 12n)); s.account(bob); await p.move(asset, { ...floor, parcelId: 743 }); assert.equal((await p.snapshot(742)).attachments.length, 0); assert.equal((await p.snapshot(743)).attachments.length, 1); await p.retrieveItem(1, 3, 12n); await p.removeContainer(1); await p.detach(asset); assert.equal(await p.ownerOf(asset), bob); await assert.rejects(p.detach(asset)); assert.equal(await s.ledger.getBalance(bob, 3n), 12n); assert.equal(await s.ledger.getBalance(alice, 3n), 8n); assert.deepEqual((await s.create().snapshot(743)).attachments, []); });
test('capacity, bounds and failed storage commit preserve custody', async () => { const s = setup(), p = s.create(), [a, b] = p.knownAssets(); await p.createContainer(742, floor, 1); await p.attach(a, { kind: 'container', parcelId: 742, containerId: 1 }); await assert.rejects(p.attach(b, { kind: 'container', parcelId: 742, containerId: 1 }), /capacity/); assert.equal(await p.ownerOf(b), alice); await assert.rejects(p.move(a, { ...floor, x: -1 })); await assert.rejects(p.move(a, { kind: 'container', parcelId: 743, containerId: 1 })); const before = await p.snapshot(742); s.storage.setItem = () => { throw new Error('quota'); }; await assert.rejects(p.detach(a), /quota/); assert.deepEqual(await p.snapshot(742), before); assert.equal(await p.ownerOf(a), MOCK_NFT_ESCROW); });
test('metadata strips executable fields, rejects unsafe URLs and handles data forms', async () => { const gateway = 'https://ipfs.io/ipfs/'; const raw = JSON.stringify({ name: '<script>hostile</script>', image: 'javascript:alert(1)', animation_url: 'https://evil.invalid', attributes: [{ trait_type: 'x', value: '<img onerror=alert(1)>' }] }); const safe = parseMetadata(raw, gateway); assert.equal(safe.image, undefined); assert.equal('animation_url' in safe, false); assert.equal(safe.name, '<script>hostile</script>'); assert.deepEqual(await loadMetadata('data:application/json;base64,' + Buffer.from(raw).toString('base64'), gateway), safe); assert.deepEqual(await loadMetadata('data:application/json;utf8,' + encodeURIComponent(raw), gateway), safe); for (const url of ['javascript:x', 'http://unsafe.test', 'data:text/html,x', 'ipfs://cid/../../evil', 'https://user:pass@test.invalid'])
    assert.throws(() => resolveURL(url, gateway)); assert.equal(resolveURL('ipfs://QmExample/image.png', gateway), 'https://ipfs.io/ipfs/QmExample/image.png'); assert.throws(() => parseMetadata('x'.repeat(140000), gateway)); await assert.rejects(loadMetadata('data:application/json;utf8,%ZZ', gateway)); });
test('metadata cache deduplicates, expires success and failure and falls back safely', async () => { let calls = 0, clock = 0; const s = setup(), asset = s.create().knownAssets()[0]; const cache = new MetadataCache(async () => { calls++; return 'data:application/json;utf8,{"name":"Art"}'; }, 'https://ipfs.io/ipfs/', () => clock); const [a, b] = await Promise.all([cache.get(asset), cache.get(asset)]); assert.equal(a, b); assert.equal(calls, 1); clock = 300001; await cache.get(asset); assert.equal(calls, 2); const broken = new MetadataCache(async () => { throw Error('CORS'); }, 'https://ipfs.io/ipfs/', () => clock); assert.equal((await broken.get(asset)).name, 'Unknown NFT'); await broken.get(asset); assert.equal(broken.hits, 1); clock += 30001; await broken.get(asset); assert.equal(broken.misses, 2); });
test('ERC1155 and exact ERC721 doors check wallet custody without consuming keys', async () => { const s = setup(), p = s.create(), asset = p.knownAssets()[0]; await p.createDoor(742, floor, { kind: 'erc1155', contractAddress: MOCK_ITEMS, tokenId: 4n, minimum: 1n, mode: 'CHECK_ONLY' }); const [door] = (await p.snapshot(742)).doors; assert.equal(await p.canOpen(door, alice), false); await s.ledger.grantDevItem(4, 1n); assert.equal(await p.canOpen(door, alice), true); assert.equal(await s.ledger.getBalance(alice, 4n), 1n); await p.createDoor(742, floor, { kind: 'erc721', contractAddress: asset.contractAddress, tokenId: asset.tokenId, mode: 'CHECK_ONLY' }); const d = (await p.snapshot(742)).doors[1]; assert.equal(await p.canOpen(d, alice), true); await p.attach(asset, floor); assert.equal(await p.canOpen(d, alice), false); assert.equal(await evaluateAccess(d.requirement, alice, { balance: async () => 0n, owner: async () => { throw Error('RPC'); } }), false); });
test('streaming renders neighboring NFTs, rejects stale reads and disposes geometry', async () => { const s = setup(), p = s.create(), asset = p.knownAssets()[0]; await p.attach(asset, floor); const scene = new THREE.Scene(), cache = new MetadataCache(a => p.tokenURI(a), 'https://ipfs.io/ipfs/'), layer = new NFTLayer(scene, p, new NFTRepresentationRegistry(), 7422026n, cache, () => { }); layer.sync([742, 743]); await layer.refresh(742); assert.equal(layer.count(), 1); let disposed = 0; layer.roots()[0].traverse(o => { if (o instanceof THREE.Mesh)
    o.geometry.addEventListener('dispose', () => disposed++); }); layer.sync([743]); assert.equal(layer.count(), 0); assert.ok(disposed > 0); let resolve!: (v: Awaited<ReturnType<NFTStateProvider['snapshot']>>) => void; const stale = new NFTLayer(scene, { ...p, snapshot: () => new Promise(r => { resolve = r; }) } as NFTStateProvider, new NFTRepresentationRegistry(), 7422026n, cache, () => { }); stale.sync([742]); stale.sync([]); resolve(await p.snapshot(742)); await new Promise(r => setTimeout(r, 0)); assert.equal(stale.parcels.size, 0); layer.dispose(); stale.dispose(); assert.equal(scene.children.length, 0); });
