<script lang="ts">
 import {onMount} from 'svelte';
 import {registerDemoTools} from '$lib/webmcp';
 import {Sprout,Wind,Droplets,ArrowUpRight,Check,Coins,Move,Leaf,Wallet,ExternalLink} from '@lucide/svelte';
 import Island from './Island.svelte';
 import {accrue,harvest,upgrade,rate,capacity,UPGRADES,type Farm as FarmState} from '$lib/farm';
 import {wallet,projectId,connect,switchNetwork} from '$lib/web3/wallet';
 import {configured,landAddress,readLand,transact,validToken,explain,type Snapshot} from '$lib/web3/contracts';
 let {onchain=false,embed=false}=$props<{onchain?:boolean;embed?:boolean}>();
 let demo=$state<FarmState>({balance:0,stored:20,updated:0,level:0});let ready=$state(false);let saved=$state(true);
 let snapshot=$state<Snapshot|null>(null);let token=$state('1');let tokenInput=$state('1');let message=$state('Your first harvest is ready. Let’s grow something.');
 let loading=$state(false);let busy=$state(false);let txHash=$state('');let chainError=$state('');let active=true;let readSequence=0;
 const icons=[Sprout,Droplets,Wind];const KEY='cloudacre-demo-v1';
 let farm=$derived(onchain?{balance:snapshot?.balance??0,stored:snapshot?.stored??0,updated:snapshot?.updated??0,level:snapshot?.level??0}:demo);
 let owned=$derived(!!snapshot&&!!$wallet.address&&snapshot.owner.toLowerCase()===$wallet.address.toLowerCase());
 let canAct=$derived(onchain?!!snapshot&&owned&&$wallet.chainId===84532&&!busy&&!loading:ready);
 let full=$derived(farm.stored>=capacity(farm.level));
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(demo))}catch{saved=false}}
 async function refresh(){const sequence=++readSequence;if(!configured||!validToken(token)){snapshot=null;chainError=!configured?'Testnet land is not connected yet.':'Enter a valid positive token ID.';return}loading=true;const requested=token;const address=$wallet.address;try{const next=await readLand(requested,address);if(active&&sequence===readSequence){snapshot=next;chainError=''}}catch(e){if(active&&sequence===readSequence){snapshot=null;chainError=explain(e)}}finally{if(active&&sequence===readSequence)loading=false}}
 onMount(()=>{active=true;if(onchain){const value=new URLSearchParams(location.search).get('token')||'1';token=value;tokenInput=value;message='Harvest and upgrade with your wallet on Base Sepolia.';void refresh()}else{try{const f=JSON.parse(localStorage.getItem(KEY)||'null');if(f&&Number.isInteger(f.level)&&f.level>=0&&f.level<=3&&Number.isFinite(f.balance)&&f.balance>=0&&Number.isFinite(f.stored)&&f.stored>=0&&Number.isFinite(f.updated)&&f.updated>0)demo=accrue(f,Date.now());else demo={...demo,updated:Date.now()}}catch{saved=false;demo={...demo,updated:Date.now()}}persist()}ready=true;
 const stopTools=onchain?()=>{}:registerDemoTools(()=>demo,f=>{demo=f;persist()});
 const timer=setInterval(()=>{if(!onchain){demo=accrue(demo,Date.now());persist()}},1000);
 const poll=setInterval(()=>{if(onchain&&!busy&&!loading)void refresh()},15000);
 return()=>{stopTools();active=false;readSequence++;clearInterval(timer);clearInterval(poll)};
 });
 $effect(()=>{const address=$wallet.address;const network=$wallet.chainId;if(ready&&onchain){snapshot=null;void refresh()}void address;void network});
 async function collect(){if(onchain){await perform('harvest');return}demo=accrue(demo,Date.now());const amount=Math.floor(demo.stored);demo=harvest(demo,Date.now());persist();message=`+${amount} SEED harvested. Your next harvest is already growing.`}
 async function buy(){if(onchain){await perform('upgrade');return}const previous=demo.level;demo=upgrade(demo,Date.now());persist();if(demo.level>previous)message=`${UPGRADES[previous].type} built! Your island earns ${rate(demo.level)} SEED per minute.`}
 async function perform(action:'mint'|'harvest'|'upgrade'){if(busy)return;busy=true;txHash='';message='Confirm the transaction in your wallet.';try{const result=await transact(action,token,hash=>{txHash=hash;message='Transaction submitted. Waiting for confirmation…'});txHash=result.receipt.hash;token=result.id;tokenInput=token;history.replaceState(null,'',`?token=${token}`);message=`${action==='mint'?'Land minted':action==='harvest'?'Harvest collected':'Upgrade built'} on Base Sepolia.`;await refresh()}catch(e){message=explain(e)}finally{busy=false}}
 async function openWallet(){try{await connect()}catch(e){message=explain(e)}}
 async function changeNetwork(){try{await switchNetwork()}catch(e){message=explain(e)}}
 function selectToken(){if(!validToken(tokenInput)){chainError='Enter a valid positive token ID.';return}token=tokenInput;snapshot=null;history.replaceState(null,'',`?token=${token}`);void refresh()}
 const short=(value:string)=>`${value.slice(0,6)}…${value.slice(-4)}`;
</script>
<svelte:head><title>{onchain?'Land NFT':'Playground'} · Cloudacre</title><meta name="description" content="Grow, harvest, and evolve a floating Three.js farm. Built with SvelteKit and Reown."/></svelte:head>
<main class:embed>
 {#if !embed}<header><a class="brand" href="/farm/"><span class="brandmark"><Sprout size={23}/></span>cloudacre<span class="beta">{onchain?'BASE SEPOLIA':'PLAYGROUND'}</span></a><nav class="topnav"><a href={onchain?'/farm/':'/nft/?token=1'}>{onchain?'Demo playground':'Testnet land'}<ArrowUpRight size={14}/></a>{#if onchain}<button class="wallet-button" onclick={openWallet} disabled={!projectId||busy}><Wallet size={15}/>{$wallet.connected&&$wallet.address?short($wallet.address):'Connect wallet'}</button>{:else}<span class="demo"><i></i>Demo world · no real tokens</span>{/if}</nav></header>{/if}
 <div class="game"><section class="world"><div class="world-heading"><div class="eyebrow">YOUR LITTLE CORNER OF THE SKY</div><h1>Windfall Island <span>#{onchain?token.padStart(3,'0'):'001'}</span></h1><div class="level"><Leaf size={14}/>{onchain&&!snapshot?'Awaiting verified land data':['The beginning','Taking root','In full bloom','A thriving acre'][farm.level]}{#if !onchain||snapshot}<span>LEVEL {farm.level+1}</span>{/if}</div></div>
 {#if !onchain||snapshot}<Island level={farm.level}/>{:else}<div class="unavailable"><Sprout size={42}/><h2>{loading?'Loading your land…':'Land preview unavailable'}</h2><p>{chainError||'Waiting for Base Sepolia.'}</p>{#if !configured}<p>Contract deployment and configuration are still needed. Explore the demo to try farming.</p>{/if}<a href="/farm/" target={embed?'_blank':undefined} rel="noreferrer">Open demo playground ↗</a></div>{/if}
 <div class="world-bottom"><span><Move size={15}/>Drag to explore · Scroll or pinch to zoom</span><span class="live"><i></i>{onchain?'Land state from Base Sepolia':'Growing, even while you’re away'}</span></div></section>
 {#if !embed}<aside class="dashboard">
 {#if onchain}<section class="chain-panel"><div class="section-row"><h2>Your testnet land</h2><span class="status">Base Sepolia</span></div><form onsubmit={e=>{e.preventDefault();selectToken()}}><label for="token">Token ID</label><div class="token-select"><input id="token" inputmode="numeric" bind:value={tokenInput} disabled={busy}/><button disabled={busy||loading}>View land</button></div></form>{#if !configured||!projectId}<p class="setup-note">{!configured?'Land contracts are not configured. ':''}{!projectId?'Wallet connection awaits a Reown project ID.':''}</p>{/if}{#if $wallet.connected&&$wallet.chainId!==84532}<button class="wallet-button" onclick={changeNetwork} disabled={busy}>Switch to Base Sepolia</button>{/if}<button class="mint-button" onclick={()=>perform('mint')} disabled={!configured||!$wallet.connected||$wallet.chainId!==84532||busy}>Mint test land <span>Free · gas required</span></button><p class="hint">One faucet mint per wallet. Test assets have no promised value.</p>{#if snapshot}<p class="owner">Owner: {short(snapshot.owner)} {owned?'· You':''}</p><a class="small-link" href={`/embed/?token=${token}`} target="_blank" rel="noreferrer">Open NFT viewer <ExternalLink size={12}/></a>{/if}</section>{/if}
 <div class="wallet"><div><span class="eyebrow">YOUR BALANCE</span><div class="balance"><Coins size={27}/>{onchain&&!snapshot?'—':Math.floor(farm.balance)}<small>SEED</small></div></div><span class="token">{onchain?'TESTNET':'DEMO'}<br/>RESOURCE</span></div>
 <section class="harvest"><div class="section-row"><h2>Your harvest</h2><span class:full class="status">{full?'Ready to collect':'Growing'}</span></div><div class="harvest-number">{onchain&&!snapshot?'—':Math.floor(farm.stored)}<span>/ {capacity(farm.level)} SEED</span></div><progress max={capacity(farm.level)} value={farm.stored} aria-label="Harvest storage"></progress><div class="harvest-meta"><span>+{rate(farm.level)} SEED / min</span><span>{full?'Storage full':onchain?'Refreshes every 15s':`${Math.ceil((capacity(farm.level)-farm.stored)/rate(farm.level))} min until full`}</span></div><button class="harvest-button" onclick={collect} disabled={!canAct||(onchain?!(snapshot&&snapshot.pendingWei>0n):farm.stored<1)}><Sprout size={20}/>{busy?'Waiting for wallet…':'Harvest SEED'}<ArrowUpRight size={19}/></button><p class="feedback" role="status">{message}</p>{#if txHash}<a class="small-link" href={`https://sepolia.basescan.org/tx/${txHash}`} target="_blank" rel="noreferrer">View transaction <ExternalLink size={12}/></a>{/if}{#if onchain&&chainError}<p role="alert" class="setup-note">{chainError}</p>{/if}{#if onchain&&snapshot&&!owned}<p class="hint">Connect the owner’s wallet to harvest or upgrade.</p>{/if}</section>
 <section class="upgrades"><div class="section-row"><h2>Room to grow</h2><span class="counter">{farm.level} / 3</span></div><p class="hint">Reinvest your harvest. Watch your land evolve.</p>{#each UPGRADES as u,i}{@const Icon=icons[i]}{@const built=farm.level>i}<div class="upgrade" class:built><span class="upgrade-icon"><Icon size={22}/></span><div class="upgrade-copy"><h3>{u.type}</h3><p>{u.description}</p><span>{u.rate} SEED / min · {u.cap} storage</span></div><button aria-label={built?`${u.type} built`:`Build ${u.type} for ${u.cost} SEED`} disabled={!canAct||farm.level!==i||(onchain?!(snapshot&&snapshot.balanceWei>=BigInt(u.cost)*10n**18n):farm.balance<u.cost)} onclick={buy}>{#if built}<Check size={19}/>{:else}{u.cost}<small>SEED</small>{/if}</button></div>{/each}</section>
 <p class="save-note">{onchain?'Upgrades and unclaimed crops stay with the NFT. Harvested SEED stays in your wallet.':saved?'Progress saves on this device. Demo resources have no monetary value.':'Storage unavailable — progress lasts for this visit.'}</p>
 </aside>{/if}</div>
 {#if !embed}<footer><span><Sprout size={15}/>A little land. A living world.</span><span>SvelteKit · Three.js · Reown</span></footer>{/if}
</main>



